import type { QuestionBlueprint } from '@/lib/assessment/blueprint/types';

export const progressiveAdditionLensesContentBlueprint: QuestionBlueprint = {
  id: 'progressive-addition-lenses-candidate-v1',
  bankId: 'progressive-addition-lenses-candidate',
  totalQuestions: 80,
  sectionTargets: {
    'measure-order': 14,
    'pal-designs': 8,
    'pal-principles': 15,
    'pal-troubleshooting': 10,
    'patient-frame': 11,
    'reference-markings': 15,
    'verification-delivery': 7,
  },
  formatTargets: {
    'extended_matching': 7,
    'image_hotspot': 5,
    'image_label': 4,
    'matching': 9,
    'multiple_response': 10,
    'open_response': 2,
    'ordering': 7,
    'short_answer': 4,
    'single_best_answer': 26,
    'true_false': 6,
  },
  bloomTargets: {
    'analyze': 7,
    'apply': 33,
    'create': 1,
    'evaluate': 3,
    'remember': 11,
    'understand': 25,
  },
  difficultyTargets: {
    'advanced': 11,
    'foundation': 24,
    'intermediate': 45,
  },
  stimulusTargets: {
    'table': 0,
    'clinical_vignette': 11,
    'comparison': 25,
    'diagram': 10,
    'error_analysis': 4,
    'pathway': 7,
    'text': 23,
  },
  minimumHigherOrderShare: 44 / 80,
  minimumQuestionsPerObjective: 2,
};

export const progressiveAdditionLensesPracticeBlueprint = {
  id: 'progressive-addition-lenses-practice-50-v1',
  bankId: 'progressive-addition-lenses-candidate',
  totalQuestions: 50,
  sectionTargets: {
    'measure-order': 9,
    'pal-designs': 5,
    'pal-principles': 10,
    'pal-troubleshooting': 6,
    'patient-frame': 7,
    'reference-markings': 9,
    'verification-delivery': 4,
  },
  formatTargets: {
    'single_best_answer': 17,
    'true_false': 4,
    'multiple_response': 6,
    'ordering': 4,
    'matching': 5,
    'extended_matching': 4,
    'image_hotspot': 3,
    'image_label': 2,
    'short_answer': 3,
    'open_response': 2,
  },
} as const;
