import type { QuestionBlueprint } from '@/lib/assessment/blueprint/types';

export const multifocalFoundationsContentBlueprint: QuestionBlueprint = {
  id: 'multifocal-foundations-candidate-v1',
  bankId: 'multifocal-foundations-candidate',
  totalQuestions: 80,
  sectionTargets: {
    'bifocal-fitting': 12,
    'construction-types': 13,
    'jump-tca': 11,
    'nvp-prism': 12,
    'presbyopia-add': 8,
    'segment-designs': 17,
    'trifocals': 7,
  },
  formatTargets: {
    'extended_matching': 7,
    'image_hotspot': 5,
    'image_label': 4,
    'matching': 9,
    'multiple_response': 10,
    'open_response': 2,
    'ordering': 7,
    'short_answer': 4,
    'single_best_answer': 26,
    'true_false': 6,
  },
  bloomTargets: {
    'analyze': 6,
    'apply': 36,
    'create': 1,
    'evaluate': 3,
    'remember': 10,
    'understand': 24,
  },
  difficultyTargets: {
    'advanced': 11,
    'foundation': 24,
    'intermediate': 45,
  },
  stimulusTargets: {
    'table': 0,
    'clinical_vignette': 6,
    'comparison': 26,
    'diagram': 9,
    'error_analysis': 4,
    'pathway': 7,
    'text': 28,
  },
  minimumHigherOrderShare: 46 / 80,
  minimumQuestionsPerObjective: 2,
};

export const multifocalFoundationsPracticeBlueprint = {
  id: 'multifocal-foundations-practice-50-v1',
  bankId: 'multifocal-foundations-candidate',
  totalQuestions: 50,
  sectionTargets: {
    'bifocal-fitting': 8,
    'construction-types': 8,
    'jump-tca': 7,
    'nvp-prism': 7,
    'presbyopia-add': 5,
    'segment-designs': 11,
    'trifocals': 4,
  },
  formatTargets: {
    'single_best_answer': 17,
    'true_false': 4,
    'multiple_response': 6,
    'ordering': 4,
    'matching': 5,
    'extended_matching': 4,
    'image_hotspot': 3,
    'image_label': 2,
    'short_answer': 3,
    'open_response': 2,
  },
} as const;
