import { extended, mr, sba, trueFalse } from '../questionFactory';
import {
  aqueousLectureSource,
  neiVitreousDetachmentSource,
  posteriorVitreousDetachmentSource,
} from '../sources';
import type { AssessmentQuestion } from '@/lib/assessment/types';

const sources = [
  aqueousLectureSource,
  neiVitreousDetachmentSource,
  posteriorVitreousDetachmentSource,
];

export const curatedVitreousClinicalQuestions: AssessmentQuestion[] = [
  sba({
    id: 'vitreous-clinical-sba-003',
    familyId: 'vitreous-acute-symptom-triage',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-evaluate-retinal-warning-signs',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'A patient reports a sudden shower of new floaters and flashes in one eye. What is the safest next step?',
    explanation: 'Acute flashes and new floaters can accompany posterior vitreous detachment and a retinal tear, so urgent dilated retinal assessment is required.',
    sources,
    misconceptionTags: ['acute-symptom-undertriage', 'iop-excludes-retinal-tear'],
  }, [
    ['urgent-retinal-exam', 'Arrange urgent dilated retinal assessment', 'This evaluates for a retinal tear or detachment.'],
    ['routine-year', 'Wait for the next annual examination', 'Delay could miss a time-sensitive retinal complication.', 'acute-symptom-undertriage'],
    ['rub-eye', 'Advise rubbing the eye until the flashes stop', 'This does not evaluate or treat the cause.', 'symptom-self-treatment'],
    ['tonometry-only', 'Measure IOP only and discharge if it is typical', 'A typical IOP does not exclude a retinal tear.', 'iop-excludes-retinal-tear'],
  ], 'urgent-retinal-exam'),
  trueFalse({
    id: 'vitreous-clinical-tf-001',
    familyId: 'pvd-retinal-tear-equivalence',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-interpret-clinical-change',
    stimulusType: 'text',
    bloomLevel: 'remember',
    difficulty: 'foundation',
    stem: 'Every posterior vitreous detachment causes a retinal tear.',
    explanation: 'False. Many PVDs do not cause a tear, but traction can produce one, which is why acute symptoms need retinal examination.',
    sources,
    misconceptionTags: ['pvd-always-tear'],
  }, false),
  mr({
    id: 'vitreous-clinical-mr-001',
    familyId: 'retinal-warning-symptom-set',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-evaluate-retinal-warning-signs',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'evaluate',
    difficulty: 'advanced',
    stem: 'Select the symptom changes that should trigger urgent assessment for a retinal tear or detachment.',
    explanation: 'Sudden new floaters, flashes, and a curtain or shadow are warning patterns. A single longstanding unchanged floater without new symptoms is not equivalent to an acute change.',
    sources,
    misconceptionTags: ['stable-acute-confusion', 'acute-symptom-undertriage'],
  }, [
    ['new-floaters', 'A sudden increase in floaters', 'An acute increase can accompany vitreous separation or hemorrhage.'],
    ['flashes', 'New flashes of light', 'Photopsia can reflect vitreoretinal traction.'],
    ['curtain', 'A new curtain-like shadow or field loss', 'This can indicate retinal detachment.'],
    ['stable-floater', 'A longstanding unchanged floater', 'This lacks the acute change described by the warning pattern.', 'stable-acute-confusion'],
  ], ['new-floaters', 'flashes', 'curtain']),
  extended({
    id: 'vitreous-clinical-extended-002',
    misconceptionTags: ['acute-symptom-undertriage'],
    familyId: 'vitreous-symptom-triage-levels',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-evaluate-retinal-warning-signs',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'evaluate',
    difficulty: 'advanced',
    stem: 'Assign the safest response to each independent symptom pattern.',
    explanation: 'A curtain-like loss requires immediate emergency assessment; new flashes and floaters require urgent dilated examination; a longstanding unchanged floater can follow routine clinician-directed review.',
    sources,
  }, [
    ['curtain-pattern', 'A new dark curtain is spreading across part of the visual field'],
    ['acute-pattern', 'New flashes and a sudden cluster of floaters without a curtain'],
    ['stable-pattern', 'One unchanged floater has been present for years and a recent retinal examination was normal'],
  ], [
    ['emergency', 'Immediate emergency retinal assessment', 'Curtain-like field loss can signal retinal detachment.'],
    ['urgent', 'Urgent dilated retinal examination', 'New flashes and floaters need prompt evaluation for a tear.'],
    ['routine', 'Routine clinician-directed follow-up', 'A longstanding unchanged symptom after recent normal evaluation does not match an acute warning pattern.'],
    ['iop-only', 'IOP measurement as the only assessment', 'Tonometry alone cannot exclude retinal pathology.', 'iop-excludes-retinal-tear'],
  ], {
    'curtain-pattern': 'emergency',
    'acute-pattern': 'urgent',
    'stable-pattern': 'routine',
  }, false),
  sba({
    id: 'vitreous-clinical-sba-004',
    familyId: 'vitreous-traction-photopsia-mechanism',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-interpret-clinical-change',
    stimulusType: 'comparison',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'During evolving posterior vitreous separation, which mechanism best explains flashes of light?',
    explanation: 'Mechanical traction on the retina can stimulate retinal tissue and be perceived as flashes.',
    sources,
    misconceptionTags: ['photopsia-mechanism-confusion'],
  }, [
    ['retinal-traction', 'Mechanical vitreoretinal traction stimulates the retina', 'Traction can generate photopsia during separation.'],
    ['aqueous-color', 'Aqueous changes colour and projects light onto the retina', 'Aqueous colour change is not the mechanism.', 'aqueous-vitreous-confusion'],
    ['lens-secretion', 'The lens secretes electrical impulses into the vitreous', 'The lens does not generate photopsia this way.', 'lens-function-confusion'],
    ['iop-zero', 'IOP falls to zero whenever the vitreous liquefies', 'Vitreous liquefaction does not imply zero IOP.', 'pressure-vitreous-confusion'],
  ], 'retinal-traction'),
  sba({
    id: 'vitreous-clinical-sba-005',
    familyId: 'vitreous-degeneration-term-correction',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-interpret-clinical-change',
    stimulusType: 'error_analysis',
    bloomLevel: 'analyze',
    difficulty: 'advanced',
    stem: 'A learner says, “Vitreous syneresis is itself a retinal tear.” Which correction is most accurate?',
    explanation: 'Age-related vitreous gel change includes liquefaction and structural collapse or aggregation. These changes can contribute to PVD and traction, but they are not themselves a retinal tear.',
    sources,
    misconceptionTags: ['vitreous-degeneration-equals-tear'],
  }, [
    ['predisposes-not-equals', 'Vitreous degeneration can predispose to separation and traction but does not equal a retinal tear', 'This preserves the causal relationship without equating distinct conditions.'],
    ['tear-synonym', 'Syneresis is simply another name for a full-thickness retinal tear', 'The terms refer to different tissues and processes.', 'vitreous-degeneration-equals-tear'],
    ['aqueous-block', 'Syneresis means aqueous is blocked at the pupil', 'Syneresis is a vitreous gel change, not pupillary block.', 'aqueous-vitreous-confusion'],
    ['normal-artery', 'Syneresis is persistence of the fetal hyaloid artery', 'This confuses gel degeneration with a developmental remnant.', 'hyaloid-degeneration-confusion'],
  ], 'predisposes-not-equals'),
  sba({
    id: 'vitreous-clinical-sba-006',
    familyId: 'pvd-worsening-symptom-reassessment',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-evaluate-retinal-warning-signs',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'A person recently diagnosed with PVD now develops many more floaters and a new peripheral shadow. What is the best interpretation?',
    explanation: 'New or worsening symptoms after PVD can indicate a retinal tear or detachment and require urgent repeat retinal assessment.',
    sources,
    misconceptionTags: ['pvd-always-benign', 'acute-symptom-undertriage'],
  }, [
    ['urgent-repeat', 'Urgent repeat retinal assessment is required', 'Worsening floaters and a shadow are warning signs.'],
    ['expected-ignore', 'This is always harmless after PVD and can be ignored', 'PVD can be complicated by retinal tear or detachment.', 'pvd-always-benign'],
    ['glaucoma-certain', 'The symptoms prove glaucoma', 'This symptom pattern is vitreoretinal, not diagnostic of glaucoma.', 'symptom-disease-confusion'],
    ['corneal-dryness', 'The shadow is best explained by tear-film evaporation alone', 'Dry-eye fluctuation does not explain a curtain-like field shadow.', 'surface-retinal-confusion'],
  ], 'urgent-repeat'),
];
