import { extended, matching, mr, ordering, sba, trueFalse } from '../questionFactory';
import { aqueousLectureSource, aqueousPhysiologySource } from '../sources';
import type { AssessmentQuestion } from '@/lib/assessment/types';

const sources = [aqueousLectureSource, aqueousPhysiologySource];

export const curatedProductionQuestions: AssessmentQuestion[] = [
  sba({
    id: 'aqueous-production-sba-002',
    familyId: 'aqueous-dominant-production-mechanism',
    sectionId: 'production',
    objectiveId: 'aqueous-explain-production',
    stimulusType: 'text',
    bloomLevel: 'remember',
    difficulty: 'foundation',
    stem: 'Which mechanism is the dominant contributor to normal aqueous humour formation?',
    explanation: 'ATP-dependent active secretion across the ciliary epithelium, with the non-pigmented layer as the final secretory surface, is the dominant mechanism. Diffusion and ultrafiltration also contribute.',
    sources,
  }, [
    ['active-secretion', 'Active secretion by the ciliary epithelium', 'This is the dominant normal production mechanism.'],
    ['passive-filtration', 'Passive filtration through the trabecular meshwork', 'The trabecular meshwork is an outflow structure, not the production site.'],
    ['vitreous-diffusion', 'Diffusion from the vitreous cavity', 'The vitreous is not the primary source of aqueous.', 'aqueous-vitreous-confusion'],
    ['corneal-pump', 'Corneal endothelial pump activity', 'This maintains corneal hydration rather than forming aqueous.', 'cornea-production-confusion'],
  ], 'active-secretion'),
  trueFalse({
    id: 'aqueous-production-tf-001',
    familyId: 'aqueous-production-passive-only',
    sectionId: 'production',
    objectiveId: 'aqueous-explain-production',
    stimulusType: 'error_analysis',
    bloomLevel: 'understand',
    difficulty: 'foundation',
    stem: 'Normal aqueous humour is produced solely by ultrafiltration from ciliary capillaries.',
    explanation: 'False. Ultrafiltration contributes, but active epithelial secretion is dominant and diffusion also contributes.',
    sources,
    misconceptionTags: ['production-passive-only'],
  }, false),
  mr({
    id: 'aqueous-production-mr-003',
    familyId: 'blood-aqueous-barrier-findings',
    sectionId: 'production',
    objectiveId: 'aqueous-predict-production-barrier-change',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'analyze',
    difficulty: 'advanced',
    stem: 'Anterior inflammation disrupts the blood-aqueous barrier. Select the findings that are directly consistent with that disruption.',
    explanation: 'Barrier breakdown permits protein and inflammatory cells into aqueous; protein scatters light as flare. It does not directly convert the vitreous into aqueous.',
    sources,
    misconceptionTags: ['barrier-pressure-only', 'aqueous-vitreous-confusion'],
  }, [
    ['protein-rise', 'Increased aqueous protein', 'A less selective barrier permits protein entry.'],
    ['cells-rise', 'Inflammatory cells in the anterior chamber', 'Barrier disruption permits cellular entry.'],
    ['flare', 'Light scatter seen as aqueous flare', 'Protein in aqueous produces light scatter.'],
    ['vitreous-conversion', 'Conversion of vitreous gel into newly secreted aqueous', 'Vitreous liquefaction is not aqueous production.', 'aqueous-vitreous-confusion'],
  ], ['protein-rise', 'cells-rise', 'flare']),
  matching({
    id: 'aqueous-production-matching-002',
    misconceptionTags: ['aqueous-function-confusion'],
    familyId: 'aqueous-function-consequence-pairs',
    sectionId: 'production',
    objectiveId: 'aqueous-explain-production',
    stimulusType: 'table',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Match each observed consequence to the aqueous-humour function most directly affected.',
    explanation: 'Aqueous supplies avascular tissues, removes metabolites and debris, and helps maintain ocular pressure and shape.',
    sources,
    table: {
      caption: 'Observed anterior-segment consequences',
      columns: [
        { id: 'case', heading: 'Case' },
        { id: 'finding', heading: 'Finding' },
      ],
      rows: [
        { id: 'case-a', cells: { case: 'A', finding: 'Reduced nutrient delivery to cornea and lens' } },
        { id: 'case-b', cells: { case: 'B', finding: 'Metabolic waste accumulates in the anterior segment' } },
        { id: 'case-c', cells: { case: 'C', finding: 'The balance supporting globe pressure is disturbed' } },
      ],
    },
  }, [
    ['case-a', 'Case A'],
    ['case-b', 'Case B'],
    ['case-c', 'Case C'],
  ], [
    ['nutrition', 'Nutrition of avascular tissues', 'Aqueous carries nutrients and oxygen to cornea and lens.'],
    ['waste-clearance', 'Waste and debris clearance', 'Aqueous circulation removes metabolites and debris.'],
    ['pressure-shape', 'Maintenance of pressure and globe shape', 'Balanced formation and outflow support pressure and shape.'],
    ['retinal-phototransduction', 'Initiation of retinal phototransduction', 'Phototransduction occurs in photoreceptors and is not an aqueous function.'],
  ], {
    'case-a': 'nutrition',
    'case-b': 'waste-clearance',
    'case-c': 'pressure-shape',
  }),
  extended({
    id: 'aqueous-production-extended-001',
    familyId: 'aqueous-production-barrier-outflow-localization',
    sectionId: 'production',
    objectiveId: 'aqueous-predict-production-barrier-change',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'analyze',
    difficulty: 'intermediate',
    stem: 'Assign the primary altered process to each independent finding.',
    explanation: 'Reduced ciliary transport lowers production, anterior protein and cells indicate barrier leakage, and a pre-canal pressure gradient indicates outflow resistance.',
    sources,
    misconceptionTags: ['production-barrier-outflow-confusion'],
  }, [
    ['transport-inhibited', 'Ciliary epithelial ion transport is inhibited and measured inflow falls'],
    ['cells-flare', 'Anterior chamber cells and flare appear during inflammation'],
    ['precanal-gradient', 'The pressure gradient rises across tissue immediately before Schlemm canal'],
  ], [
    ['reduced-production', 'Reduced active production', 'Inhibiting ciliary epithelial transport lowers secretion.'],
    ['barrier-breakdown', 'Blood-aqueous barrier breakdown', 'Protein and cells in aqueous indicate barrier leakage.'],
    ['outflow-resistance', 'Increased conventional outflow resistance', 'A raised pre-canal gradient localizes resistance to conventional outflow.'],
    ['vitreous-collapse', 'Age-related vitreous collapse', 'This does not explain the listed aqueous findings.', 'aqueous-vitreous-confusion'],
  ], {
    'transport-inhibited': 'reduced-production',
    'cells-flare': 'barrier-breakdown',
    'precanal-gradient': 'outflow-resistance',
  }, false),
  ordering({
    id: 'aqueous-production-ordering-002',
    misconceptionTags: ['ciliary-secretion-order'],
    familyId: 'aqueous-ciliary-bilayer-route',
    sectionId: 'production',
    objectiveId: 'aqueous-explain-production',
    stimulusType: 'pathway',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Arrange the simplified route from the ciliary circulation to release of newly formed aqueous.',
    explanation: 'Material moves from fenestrated ciliary capillaries into the stroma, through the pigmented and non-pigmented epithelial bilayer, and is released into the posterior chamber.',
    sources,
  }, [
    ['capillary', 'Fenestrated ciliary-process capillaries', 'The ciliary circulation provides starting material.'],
    ['stroma', 'Ciliary-process stroma and interstitium', 'Capillary filtrate enters the stromal compartment.'],
    ['pigmented', 'Pigmented ciliary epithelium', 'This is the outer epithelial layer of the bilayer.'],
    ['nonpigmented', 'Non-pigmented ciliary epithelium', 'This tight-junction layer forms the final secretory surface.'],
    ['posterior-chamber', 'Posterior chamber', 'Newly formed aqueous is released here.'],
  ], ['capillary', 'stroma', 'pigmented', 'nonpigmented', 'posterior-chamber']),
  sba({
    id: 'aqueous-production-sba-003',
    familyId: 'aqueous-avascular-tissue-support',
    sectionId: 'production',
    objectiveId: 'aqueous-explain-production',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'A sustained fall in aqueous production most directly reduces metabolic support to which pair of avascular structures?',
    explanation: 'Aqueous supplies nutrients and oxygen and removes waste for the avascular cornea and crystalline lens.',
    sources,
    misconceptionTags: ['aqueous-function-confusion', 'vascularity-confusion'],
  }, [
    ['cornea-lens', 'Cornea and crystalline lens', 'Both are avascular and depend partly on aqueous for metabolic exchange.'],
    ['iris-ciliary', 'Iris and ciliary body', 'Both have vascular supplies.', 'vascularity-confusion'],
    ['choroid-retina', 'Choroid and inner retina', 'These have specialized vascular circulations and are not the intended anterior-segment pair.', 'posterior-circulation-confusion'],
    ['sclera-optic-nerve', 'Sclera and optic nerve', 'These are not the avascular structures chiefly supported by aqueous.', 'aqueous-function-confusion'],
  ], 'cornea-lens'),
];
