import { label, matching, mr, ordering, sba, trueFalse } from '../questionFactory';
import {
  aqueousLectureSource,
  eyeAnatomySource,
  posteriorVitreousDetachmentSource,
  vitreousCompositionSource,
} from '../sources';
import type { AssessmentQuestion } from '@/lib/assessment/types';

const anatomySources = [
  aqueousLectureSource,
  eyeAnatomySource,
  posteriorVitreousDetachmentSource,
  vitreousCompositionSource,
];
const attachmentImage = {
  src: '/images/modules/aqueous/assessment/vitreous-attachments.svg',
  alt: 'Neutral sagittal eye diagram with targets at the vitreous base, posterior lens surface, optic disc, and posterior vitreous cortex.',
  width: 1200,
  height: 675,
};

export const curatedVitreousAnatomyQuestions: AssessmentQuestion[] = [
  sba({
    id: 'vitreous-anatomy-sba-002',
    familyId: 'vitreous-strongest-attachment',
    sectionId: 'vitreous-anatomy',
    objectiveId: 'vitreous-identify-anatomy',
    stimulusType: 'text',
    bloomLevel: 'remember',
    difficulty: 'foundation',
    stem: 'Where is vitreous attachment normally strongest?',
    explanation: 'The vitreous base, spanning the region around the ora serrata, is the strongest normal vitreoretinal attachment.',
    sources: anatomySources,
  }, [
    ['vitreous-base', 'Vitreous base', 'This is the strongest attachment site.'],
    ['foveal-center', 'Foveal centre', 'Macular attachment can be clinically important but is not the strongest normal attachment.', 'attachment-strength-confusion'],
    ['optic-disc', 'Optic disc margin', 'This is an attachment site but is weaker than the vitreous base.', 'attachment-strength-confusion'],
    ['hyaloid-canal', 'Hyaloid canal lumen', 'The canal is an internal landmark, not the strongest vitreoretinal attachment.', 'landmark-attachment-confusion'],
  ], 'vitreous-base'),
  trueFalse({
    id: 'vitreous-anatomy-tf-001',
    familyId: 'hyaloid-canal-adult-artery',
    sectionId: 'vitreous-anatomy',
    objectiveId: 'vitreous-identify-anatomy',
    stimulusType: 'text',
    bloomLevel: 'understand',
    difficulty: 'foundation',
    stem: 'In the normal adult eye, the hyaloid canal contains a patent hyaloid artery carrying blood to the crystalline lens.',
    explanation: 'False. The canal marks the fetal hyaloid vascular route; the artery normally regresses before birth.',
    sources: anatomySources,
    misconceptionTags: ['fetal-adult-hyaloid-confusion'],
  }, false),
  mr({
    id: 'vitreous-anatomy-mr-001',
    familyId: 'vitreous-gel-composition',
    sectionId: 'vitreous-anatomy',
    objectiveId: 'vitreous-explain-structure-attachments',
    stimulusType: 'comparison',
    bloomLevel: 'apply',
    difficulty: 'advanced',
    stem: 'Select the components or properties that explain how the vitreous can be mostly water yet behave as a transparent gel.',
    explanation: 'A sparse collagen framework and hyaluronan-rich matrix organize a very high water content while maintaining transparency. The normal vitreous is not sustained by a dense internal vascular network.',
    sources: anatomySources,
    misconceptionTags: ['vitreous-vascularity-confusion', 'water-means-unstructured'],
  }, [
    ['water', 'Very high water content', 'Water forms most of the vitreous volume.'],
    ['collagen', 'A sparse collagen fibril network', 'Collagen contributes structural organization.'],
    ['hyaluronan', 'Hyaluronan and associated macromolecules', 'These help retain water and separate collagen fibrils.'],
    ['dense-vessels', 'A dense permanent vascular network throughout the gel', 'Normal mature vitreous is avascular.', 'vitreous-vascularity-confusion'],
  ], ['water', 'collagen', 'hyaluronan']),
  matching({
    id: 'vitreous-anatomy-matching-002',
    misconceptionTags: ['vitreous-landmark-confusion'],
    familyId: 'vitreous-landmark-relations',
    sectionId: 'vitreous-anatomy',
    objectiveId: 'vitreous-explain-structure-attachments',
    stimulusType: 'table',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Match each vitreous landmark to its defining anatomical relationship.',
    explanation: 'The vitreous base surrounds the ora serrata, the hyaloid fossa cups the posterior lens, the hyaloid canal follows the fetal vascular route, and the retrohyaloid space is a potential space behind the posterior vitreous cortex.',
    sources: anatomySources,
    table: {
      caption: 'Vitreous landmarks',
      columns: [
        { id: 'landmark', heading: 'Landmark' },
        { id: 'clue', heading: 'Neutral clue' },
      ],
      rows: [
        { id: 'base-row', cells: { landmark: 'Region A', clue: 'Straddles the ora serrata' } },
        { id: 'fossa-row', cells: { landmark: 'Region B', clue: 'Saucer-shaped depression against the posterior lens' } },
        { id: 'canal-row', cells: { landmark: 'Region C', clue: 'Central route from optic disc toward posterior lens' } },
        { id: 'retro-row', cells: { landmark: 'Region D', clue: 'Potential space behind posterior vitreous cortex' } },
      ],
    },
  }, [
    ['base-row', 'Region A'],
    ['fossa-row', 'Region B'],
    ['canal-row', 'Region C'],
    ['retro-row', 'Region D'],
  ], [
    ['vitreous-base', 'Vitreous base', 'This attachment straddles the ora serrata.'],
    ['hyaloid-fossa', 'Hyaloid fossa', 'This depression accommodates the posterior lens.'],
    ['hyaloid-canal', 'Hyaloid canal', 'This follows the fetal vascular route.'],
    ['retrohyaloid-space', 'Retrohyaloid space', 'This potential space lies behind the posterior vitreous cortex.'],
  ], {
    'base-row': 'vitreous-base',
    'fossa-row': 'hyaloid-fossa',
    'canal-row': 'hyaloid-canal',
    'retro-row': 'retrohyaloid-space',
  }),
  ordering({
    id: 'vitreous-anatomy-ordering-002',
    misconceptionTags: ['fetal-adult-hyaloid-confusion'],
    familyId: 'fetal-hyaloid-artery-course',
    sectionId: 'vitreous-anatomy',
    objectiveId: 'vitreous-identify-anatomy',
    stimulusType: 'pathway',
    bloomLevel: 'understand',
    difficulty: 'intermediate',
    stem: 'During fetal life, arrange the hyaloid vascular route from its posterior origin toward the developing lens.',
    explanation: 'The hyaloid artery arose near the optic-disc/central retinal arterial region, traversed the hyaloid canal, and reached the posterior lens before normally regressing.',
    sources: anatomySources,
  }, [
    ['optic-disc-origin', 'Optic-disc or central retinal arterial region', 'This is the posterior origin.'],
    ['hyaloid-canal', 'Hyaloid canal through the vitreous', 'The vessel traversed this central route.'],
    ['posterior-lens', 'Posterior surface of the developing lens', 'The fetal vessel supplied the developing lens.'],
  ], ['optic-disc-origin', 'hyaloid-canal', 'posterior-lens']),
  label({
    id: 'vitreous-anatomy-label-002',
    misconceptionTags: ['vitreous-attachment-confusion'],
    familyId: 'vitreous-attachment-map',
    sectionId: 'vitreous-anatomy',
    objectiveId: 'vitreous-explain-structure-attachments',
    stimulusType: 'diagram',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Label the major vitreous relationships shown on the neutral sagittal diagram.',
    explanation: 'The vitreous base lies around the ora serrata, the hyaloid fossa abuts the posterior lens, and posterior relationships include the optic disc and posterior vitreous cortex.',
    sources: anatomySources,
  }, attachmentImage, [
    { id: 'target-base', label: 'Target A around the ora serrata', x: 0.40, y: 0.65 },
    { id: 'target-fossa', label: 'Target B immediately behind the lens', x: 0.48, y: 0.46 },
    { id: 'target-disc', label: 'Target C at the optic disc', x: 0.84, y: 0.48 },
    { id: 'target-cortex', label: 'Target D along the posterior vitreous surface', x: 0.74, y: 0.25 },
  ], [
    ['vitreous-base', 'Vitreous base', 'This is the strongest attachment around the ora serrata.'],
    ['hyaloid-fossa', 'Hyaloid fossa', 'This is the depression against the posterior lens.'],
    ['optic-disc', 'Optic disc', 'This is a posterior attachment landmark.'],
    ['posterior-cortex', 'Posterior vitreous cortex', 'This is the outer posterior vitreous surface.'],
  ], {
    'target-base': 'vitreous-base',
    'target-fossa': 'hyaloid-fossa',
    'target-disc': 'optic-disc',
    'target-cortex': 'posterior-cortex',
  }),
  sba({
    id: 'vitreous-anatomy-sba-003',
    familyId: 'vitreous-aqueous-iop-role',
    sectionId: 'vitreous-anatomy',
    objectiveId: 'vitreous-explain-structure-attachments',
    stimulusType: 'comparison',
    bloomLevel: 'understand',
    difficulty: 'intermediate',
    stem: 'Why do aqueous dynamics, rather than normal short-term changes in vitreous volume, chiefly regulate IOP?',
    explanation: 'Vitreous is a relatively fixed-volume gel, while aqueous is continuously produced and drained; the balance of that inflow and outflow chiefly determines IOP.',
    sources: anatomySources,
    misconceptionTags: ['aqueous-vitreous-confusion', 'pressure-volume-confusion'],
  }, [
    ['aqueous-dynamic', 'Aqueous is continuously produced and drained, whereas vitreous volume is relatively fixed', 'This explains the different pressure-regulation roles.'],
    ['vitreous-pumped', 'Vitreous is pumped through Schlemm canal every few minutes', 'Vitreous does not normally use the aqueous outflow pathway.', 'aqueous-vitreous-confusion'],
    ['lens-secretory', 'The lens secretes vitreous to set IOP', 'The lens is not a vitreous secretory pump.', 'lens-secretion-confusion'],
    ['retina-tonometer', 'The retina directly controls tonometer calibration', 'Retinal tissue does not set the measurement calibration.', 'measurement-anatomy-confusion'],
  ], 'aqueous-dynamic'),
];
