import { extended, label, matching, mr, sba, short, trueFalse } from '../questionFactory';
import {
  aqueousLectureSource,
  aqueousPhysiologySource,
  intraocularPressureSource,
} from '../sources';
import type { AssessmentQuestion } from '@/lib/assessment/types';

const sources = [aqueousLectureSource, aqueousPhysiologySource, intraocularPressureSource];
const iopImage = {
  src: '/images/modules/aqueous/assessment/iop-determinants.svg',
  alt: 'Neutral anterior-segment schematic with targets at the ciliary processes, trabecular resistance region, and episcleral venous outlet.',
  width: 1200,
  height: 675,
};

export const curatedIopQuestions: AssessmentQuestion[] = [
  sba({
    id: 'aqueous-iop-sba-003',
    familyId: 'iop-tonometry-definition',
    sectionId: 'iop',
    objectiveId: 'aqueous-identify-iop-measurement',
    stimulusType: 'text',
    bloomLevel: 'remember',
    difficulty: 'foundation',
    stem: 'What does clinical tonometry estimate?',
    explanation: 'Tonometry estimates intraocular pressure indirectly, commonly by relating force to corneal deformation or applanation.',
    sources,
  }, [
    ['iop', 'Intraocular pressure', 'This is the quantity estimated by tonometry.'],
    ['aqueous-rate', 'Aqueous production rate directly', 'Tonometry does not directly measure production.', 'measurement-production-confusion'],
    ['retinal-flow', 'Retinal blood flow directly', 'Tonometry is not a retinal blood-flow test.', 'pressure-perfusion-confusion'],
    ['vitreous-volume', 'Vitreous volume directly', 'Vitreous volume is not the direct tonometric measurement.', 'pressure-volume-confusion'],
  ], 'iop'),
  trueFalse({
    id: 'aqueous-iop-tf-001',
    familyId: 'iop-glaucoma-equivalence',
    sectionId: 'iop',
    objectiveId: 'aqueous-identify-iop-measurement',
    stimulusType: 'error_analysis',
    bloomLevel: 'understand',
    difficulty: 'foundation',
    stem: 'A single intraocular-pressure value by itself is sufficient to define whether a person has glaucoma.',
    explanation: 'False. IOP is an important risk factor and treatment target, but glaucoma is an optic neuropathy assessed with optic-nerve and visual-function evidence in clinical context.',
    sources,
    misconceptionTags: ['iop-equals-glaucoma'],
  }, false),
  mr({
    id: 'aqueous-iop-mr-002',
    familyId: 'iop-serial-comparison-controls',
    sectionId: 'iop',
    objectiveId: 'aqueous-interpret-iop-measurement-context',
    stimulusType: 'comparison',
    bloomLevel: 'apply',
    difficulty: 'advanced',
    stem: 'Select the controls that make serial IOP readings more interpretable.',
    explanation: 'Time of day, posture, measurement method, and corneal properties can affect readings. Comparable technique and context improve interpretation.',
    sources,
    misconceptionTags: ['serial-iop-context-ignored'],
  }, [
    ['same-time', 'Measure at comparable times of day', 'IOP can vary diurnally.'],
    ['same-posture-method', 'Record posture and use a comparable method', 'Posture and tonometric method affect comparability.'],
    ['consider-cornea', 'Consider central corneal thickness and corneal biomechanics', 'Corneal properties can influence measured values.'],
    ['room-color', 'Match the colour of the examination-room walls', 'Wall colour is not a recognized determinant of IOP measurement.', 'irrelevant-context-factor'],
  ], ['same-time', 'same-posture-method', 'consider-cornea']),
  matching({
    id: 'aqueous-iop-matching-002',
    misconceptionTags: ['iop-determinant-confusion'],
    familyId: 'iop-determinant-localization',
    sectionId: 'iop',
    objectiveId: 'aqueous-relate-iop-determinants',
    stimulusType: 'table',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Match each change to the IOP determinant or measurement factor it most directly represents.',
    explanation: 'IOP reflects production, outflow resistance, and episcleral venous pressure; corneal properties can bias tonometric estimation without being one of those fluid-dynamic determinants.',
    sources,
    table: {
      caption: 'Independent experimental changes',
      columns: [
        { id: 'change', heading: 'Change' },
        { id: 'finding', heading: 'Finding' },
      ],
      rows: [
        { id: 'row-a', cells: { change: 'A', finding: 'Ciliary epithelial secretion increases' } },
        { id: 'row-b', cells: { change: 'B', finding: 'Juxtacanalicular resistance increases' } },
        { id: 'row-c', cells: { change: 'C', finding: 'Episcleral venous pressure increases' } },
        { id: 'row-d', cells: { change: 'D', finding: 'Corneal thickness alters applanation behaviour' } },
      ],
    },
  }, [
    ['row-a', 'Change A'],
    ['row-b', 'Change B'],
    ['row-c', 'Change C'],
    ['row-d', 'Change D'],
  ], [
    ['production', 'Aqueous production', 'Ciliary secretion sets the inflow term.'],
    ['resistance', 'Conventional outflow resistance', 'Juxtacanalicular tissue contributes to resistance.'],
    ['venous-pressure', 'Episcleral venous pressure', 'This is the downstream pressure boundary.'],
    ['measurement-context', 'Tonometric measurement context', 'Corneal properties affect measured values rather than being an aqueous-flow determinant.'],
  ], {
    'row-a': 'production',
    'row-b': 'resistance',
    'row-c': 'venous-pressure',
    'row-d': 'measurement-context',
  }),
  extended({
    id: 'aqueous-iop-extended-002',
    misconceptionTags: ['iop-pattern-overdiagnosis'],
    familyId: 'iop-clinical-pattern-classification',
    sectionId: 'iop',
    objectiveId: 'aqueous-interpret-iop-measurement-context',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'evaluate',
    difficulty: 'advanced',
    stem: 'Choose the most defensible interpretation of each independent pattern. Full clinical correlation remains necessary for each pattern.',
    explanation: 'Raised IOP without glaucomatous damage is an ocular-hypertension pattern; glaucomatous damage can occur at statistically typical IOP; and an isolated context-sensitive reading requires confirmation before classification.',
    sources,
  }, [
    ['high-no-damage', 'Repeatedly elevated IOP while optic-nerve and field assessments remain within expected limits'],
    ['damage-typical-iop', 'Characteristic glaucomatous damage despite IOP readings within a common statistical range'],
    ['single-posture', 'One high reading obtained after a posture change, without comparable repeat measurement'],
  ], [
    ['ocular-hypertension-pattern', 'Ocular-hypertension pattern', 'Elevated pressure without demonstrated glaucomatous damage fits this pattern.'],
    ['normal-tension-pattern', 'Normal-tension glaucoma pattern', 'Glaucomatous damage can occur without an elevated office IOP.'],
    ['contextual-recheck', 'Context-dependent isolated reading requiring confirmation', 'A single context-sensitive measurement should be repeated and interpreted with examination findings.'],
    ['pvd-pattern', 'Posterior vitreous detachment pattern', 'PVD is defined by vitreous separation and symptoms, not this pressure pattern.', 'pressure-vitreous-confusion'],
  ], {
    'high-no-damage': 'ocular-hypertension-pattern',
    'damage-typical-iop': 'normal-tension-pattern',
    'single-posture': 'contextual-recheck',
  }, false),
  label({
    id: 'aqueous-iop-label-001',
    misconceptionTags: ['iop-determinant-confusion'],
    familyId: 'iop-determinants-diagram',
    sectionId: 'iop',
    objectiveId: 'aqueous-relate-iop-determinants',
    stimulusType: 'diagram',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Label the three sites representing the principal aqueous-dynamic determinants of IOP.',
    explanation: 'Ciliary epithelial secretion determines inflow, the trabecular/juxtacanalicular region contributes outflow resistance, and episcleral venous pressure sets a downstream pressure boundary.',
    sources,
  }, iopImage, [
    { id: 'target-production', label: 'Target A at the ciliary processes', x: 0.70, y: 0.62 },
    { id: 'target-resistance', label: 'Target B at the trabecular region', x: 0.27, y: 0.56 },
    { id: 'target-venous', label: 'Target C at the episcleral venous outlet', x: 0.11, y: 0.39 },
  ], [
    ['production', 'Aqueous production', 'The ciliary epithelium provides aqueous inflow.'],
    ['resistance', 'Outflow resistance', 'The trabecular/juxtacanalicular region is a principal resistance site.'],
    ['venous', 'Episcleral venous pressure', 'The downstream venous pressure opposes conventional drainage.'],
    ['vitreous-volume', 'Vitreous volume', 'Vitreous volume is relatively fixed and is not one of these aqueous-dynamic targets.', 'pressure-volume-confusion'],
  ], {
    'target-production': 'production',
    'target-resistance': 'resistance',
    'target-venous': 'venous',
  }),
  short({
    id: 'aqueous-iop-short-answer-002',
    misconceptionTags: ['episcleral-pressure-ignored'],
    familyId: 'iop-downstream-pressure-name',
    sectionId: 'iop',
    objectiveId: 'aqueous-relate-iop-determinants',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'The trabecular pathway is patent, but pressure in the receiving surface veins rises and opposes aqueous drainage. Name this downstream IOP determinant.',
    explanation: 'Episcleral venous pressure is the downstream pressure boundary for conventional aqueous outflow.',
    sources,
  }, ['episcleral venous pressure', 'EVP']),
  sba({
    id: 'aqueous-iop-sba-004',
    familyId: 'iop-corneal-context-interpretation',
    sectionId: 'iop',
    objectiveId: 'aqueous-interpret-iop-measurement-context',
    stimulusType: 'error_analysis',
    bloomLevel: 'evaluate',
    difficulty: 'intermediate',
    stem: 'One eye measures 22 mmHg and the fellow eye 17 mmHg, but the corneas differ substantially in thickness. Which conclusion is most defensible?',
    explanation: 'The difference should be interpreted with corneal properties, method, repeat measurements, and the rest of the examination; it cannot automatically be assigned entirely to true fluid pressure.',
    sources,
    misconceptionTags: ['tonometry-equals-direct-pressure'],
  }, [
    ['interpret-context', 'Interpret the difference with corneal properties and confirm it in clinical context', 'Corneal thickness can influence tonometric readings.'],
    ['certain-glaucoma', 'The 22 mmHg eye certainly has glaucoma', 'IOP alone does not establish glaucomatous damage.', 'iop-equals-glaucoma'],
    ['ignore-cornea', 'Corneal properties cannot affect any tonometric reading', 'Corneal thickness and biomechanics can influence estimation.', 'corneal-context-ignored'],
    ['vitreous-cause', 'The entire difference must come from vitreous volume', 'Vitreous volume is relatively fixed and does not explain the measurement context.', 'pressure-volume-confusion'],
  ], 'interpret-context'),
];
