import { extended, hotspot, matching, mr, ordering, sba, trueFalse } from '../questionFactory';
import { aqueousLectureSource, aqueousPhysiologySource } from '../sources';
import type { AssessmentQuestion } from '@/lib/assessment/types';

const sources = [aqueousLectureSource, aqueousPhysiologySource];
const outflowImage = {
  src: '/images/modules/aqueous/assessment/conventional-outflow.svg',
  alt: 'Neutral anterior-segment diagram with markers at the pupil, trabecular meshwork, Schlemm canal, collector channels, and ciliary muscle.',
  width: 1200,
  height: 675,
};

export const curatedFlowQuestions: AssessmentQuestion[] = [
  sba({
    id: 'aqueous-flow-sba-003',
    familyId: 'aqueous-schlemm-pathway-membership',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    stimulusType: 'text',
    bloomLevel: 'understand',
    difficulty: 'foundation',
    stem: 'Schlemm canal is part of which aqueous outflow pathway?',
    explanation: 'Schlemm canal lies in the conventional trabecular pathway after the trabecular meshwork and before collector channels.',
    sources,
  }, [
    ['conventional', 'Conventional trabecular pathway', 'This pathway includes trabecular meshwork and Schlemm canal.'],
    ['uveoscleral', 'Unconventional uveoscleral pathway', 'This route passes through uveal meshwork and ciliary muscle rather than Schlemm canal.', 'pathway-confusion'],
    ['vitreoretinal', 'Vitreoretinal pathway', 'This is not an aqueous drainage pathway.', 'aqueous-vitreous-confusion'],
    ['lacrimal', 'Lacrimal drainage pathway', 'This drains tears from the ocular surface, not aqueous from the anterior chamber.', 'tear-aqueous-confusion'],
  ], 'conventional'),
  trueFalse({
    id: 'aqueous-flow-tf-001',
    familyId: 'aqueous-outflow-route-equivalence',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    stimulusType: 'comparison',
    bloomLevel: 'understand',
    difficulty: 'foundation',
    stem: 'The conventional trabecular pathway and the unconventional uveoscleral pathway are two names for the same anatomical route.',
    explanation: 'False. Conventional outflow passes through trabecular meshwork and Schlemm canal, while uveoscleral outflow passes through the uveal meshwork and ciliary muscle toward suprachoroidal tissues.',
    sources,
    misconceptionTags: ['outflow-pathways-equated'],
  }, false),
  mr({
    id: 'aqueous-flow-mr-002',
    familyId: 'aqueous-outflow-route-features',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    stimulusType: 'comparison',
    bloomLevel: 'analyze',
    difficulty: 'advanced',
    stem: 'Select the statements that correctly compare conventional and unconventional aqueous outflow.',
    explanation: 'Conventional outflow uses trabecular meshwork and Schlemm canal; unconventional outflow traverses uveal meshwork and ciliary muscle. Both receive aqueous from the anterior chamber but remain anatomically distinct.',
    sources,
    misconceptionTags: ['outflow-pathways-equated', 'outflow-origin-confusion'],
  }, [
    ['conventional-schlemm', 'Conventional outflow includes Schlemm canal', 'Schlemm canal is a defining conventional structure.'],
    ['unconventional-muscle', 'Unconventional outflow can pass through ciliary muscle interstitium', 'This describes the uveoscleral route.'],
    ['both-anterior', 'Both routes receive aqueous after it reaches the anterior chamber', 'The pathways diverge from aqueous in the anterior chamber.'],
    ['both-vitreous', 'Both routes begin by draining vitreous through the pupil', 'They drain aqueous, not vitreous.', 'aqueous-vitreous-confusion'],
  ], ['conventional-schlemm', 'unconventional-muscle', 'both-anterior']),
  matching({
    id: 'aqueous-flow-matching-002',
    misconceptionTags: ['outflow-sequence-confusion'],
    familyId: 'aqueous-conventional-structure-roles',
    sectionId: 'flow',
    objectiveId: 'aqueous-identify-outflow-resistance',
    stimulusType: 'pathway',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Match each conventional outflow structure to its most direct role in the pathway.',
    explanation: 'The trabecular meshwork provides the principal pre-canal resistance, Schlemm canal receives angle outflow, collector channels conduct it outward, and episcleral veins return it to the venous circulation.',
    sources,
  }, [
    ['tm', 'Trabecular meshwork'],
    ['schlemm', 'Schlemm canal'],
    ['collectors', 'Collector channels'],
    ['episcleral', 'Episcleral veins'],
  ], [
    ['principal-resistance', 'Principal pre-canal resistance region', 'This is chiefly associated with the trabecular/juxtacanalicular region.'],
    ['circumferential-canal', 'Circumferential canal receiving trabecular outflow', 'This describes Schlemm canal.'],
    ['outlet-conduits', 'Conduits carrying fluid from the canal toward veins', 'This describes collector channels.'],
    ['venous-return', 'Downstream venous return and pressure boundary', 'This describes the episcleral venous system.'],
    ['aqueous-production', 'Active aqueous production surface', 'Production occurs at ciliary epithelium, not in these outflow structures.'],
  ], {
    tm: 'principal-resistance',
    schlemm: 'circumferential-canal',
    collectors: 'outlet-conduits',
    episcleral: 'venous-return',
  }),
  extended({
    id: 'aqueous-flow-extended-002',
    misconceptionTags: ['outflow-localization-confusion'],
    familyId: 'aqueous-outflow-obstruction-localization',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'analyze',
    difficulty: 'advanced',
    stem: 'Assign the best route or constraint to each independent tracer finding.',
    explanation: 'Pre-canal slowing localizes conventional resistance, passage through ciliary muscle identifies uveoscleral outflow, and raised episcleral pressure is a downstream constraint rather than another route.',
    sources,
  }, [
    ['precanal', 'Tracer slows in juxtacanalicular tissue immediately before Schlemm canal'],
    ['muscle', 'Tracer passes between ciliary muscle bundles toward suprachoroidal tissue'],
    ['venous', 'The angle remains patent but episcleral venous pressure rises'],
  ], [
    ['conventional-resistance', 'Conventional pre-canal resistance', 'The juxtacanalicular region is a principal conventional resistance site.'],
    ['uveoscleral-route', 'Unconventional uveoscleral route', 'Ciliary muscle interstitium is characteristic of this route.'],
    ['episcleral-constraint', 'Downstream episcleral venous-pressure constraint', 'Raised venous pressure opposes conventional drainage.'],
    ['pupillary-production', 'Increased production at the pupil', 'The pupil is a passage, not the production site.', 'pupil-production-confusion'],
  ], {
    precanal: 'conventional-resistance',
    muscle: 'uveoscleral-route',
    venous: 'episcleral-constraint',
  }, false),
  ordering({
    id: 'aqueous-flow-ordering-002',
    misconceptionTags: ['uveoscleral-sequence-confusion'],
    familyId: 'aqueous-uveoscleral-route-sequence',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    stimulusType: 'pathway',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Arrange the simplified unconventional uveoscleral route from the anterior chamber outward.',
    explanation: 'Aqueous enters the uveal meshwork, traverses ciliary muscle interstitium, reaches suprachoroidal tissues, and then exits across scleral or vascular pathways.',
    sources,
  }, [
    ['anterior-chamber', 'Anterior chamber', 'This supplies aqueous to the angle and both outflow routes.'],
    ['uveal-meshwork', 'Uveal meshwork', 'This is the unconventional route entrance.'],
    ['ciliary-muscle', 'Ciliary muscle interstitium', 'Aqueous passes between muscle bundles.'],
    ['suprachoroidal', 'Suprachoroidal tissue', 'This is a downstream unconventional compartment.'],
    ['scleral-vascular-exit', 'Scleral or vascular exit', 'Fluid ultimately reaches systemic routes.'],
  ], ['anterior-chamber', 'uveal-meshwork', 'ciliary-muscle', 'suprachoroidal', 'scleral-vascular-exit']),
  hotspot({
    id: 'aqueous-flow-hotspot-002',
    familyId: 'aqueous-trabecular-diagram-localization',
    sectionId: 'flow',
    objectiveId: 'aqueous-identify-outflow-resistance',
    stimulusType: 'diagram',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Select the marker over the trabecular meshwork, the principal pre-canal resistance region.',
    explanation: 'The trabecular meshwork lies at the iridocorneal angle immediately before Schlemm canal.',
    sources,
    misconceptionTags: ['outflow-sequence-confusion'],
  }, outflowImage, [
    { id: 'pupil', label: 'Pupil marker', interactionLabel: 'Marker A at the pupil', marker: 'A', x: 0.43, y: 0.37, width: 0.10, height: 0.18 },
    { id: 'trabecular', label: 'Trabecular meshwork marker', interactionLabel: 'Marker B at the angle before the canal', marker: 'B', x: 0.20, y: 0.54, width: 0.11, height: 0.16 },
    { id: 'schlemm', label: 'Schlemm canal marker', interactionLabel: 'Marker C in the circumferential canal', marker: 'C', x: 0.13, y: 0.50, width: 0.10, height: 0.15 },
    { id: 'ciliary-muscle', label: 'Ciliary muscle marker', interactionLabel: 'Marker D in the ciliary muscle', marker: 'D', x: 0.29, y: 0.67, width: 0.15, height: 0.16 },
  ], ['trabecular']),
  sba({
    id: 'aqueous-flow-sba-004',
    familyId: 'aqueous-episcleral-gradient-effect',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Aqueous production and trabecular resistance are unchanged, but episcleral venous pressure rises. What is the most direct expected effect?',
    explanation: 'Higher downstream venous pressure reduces the pressure gradient for conventional outflow and tends to raise IOP.',
    sources,
    misconceptionTags: ['episcleral-pressure-ignored', 'determinant-confusion'],
  }, [
    ['outflow-opposed', 'Conventional outflow is opposed and IOP tends to rise', 'A higher downstream pressure reduces the drainage gradient.'],
    ['production-stops', 'Ciliary epithelial secretion immediately stops', 'The changed variable is downstream venous pressure, not production.', 'determinant-confusion'],
    ['vitreous-drains', 'Vitreous drains into the episcleral veins', 'Episcleral veins receive aqueous from collector channels, not vitreous.', 'aqueous-vitreous-confusion'],
    ['angle-deepens', 'The anterior chamber must deepen without any pressure effect', 'The scenario directly changes a pressure boundary for outflow.', 'pressure-anatomy-confusion'],
  ], 'outflow-opposed'),
  sba({
    id: 'aqueous-flow-sba-005',
    familyId: 'aqueous-outflow-proportion-qualification',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    stimulusType: 'error_analysis',
    bloomLevel: 'analyze',
    difficulty: 'advanced',
    stem: 'A learner treats the lecture deck’s approximate 90/10 conventional-to-unconventional split as an invariant in every eye and condition. Which correction is best?',
    explanation: 'The deck’s split is a teaching approximation. Both routes are real, but their relative contributions vary with physiology, measurement method, age, and treatment.',
    sources,
    misconceptionTags: ['outflow-split-invariant'],
  }, [
    ['variable-proportions', 'Keep the two pathways distinct, but treat their percentage contributions as variable', 'This preserves the anatomy without overstating an approximate split.'],
    ['delete-unconventional', 'Discard the unconventional pathway because only the conventional route is real', 'Both pathways contribute to aqueous outflow.', 'unconventional-route-denial'],
    ['reverse-all-eyes', 'Apply a fixed 10/90 split to every eye instead', 'Replacing one invariant with another remains incorrect.', 'outflow-split-invariant'],
    ['merge-pathways', 'Combine both pathways into one route through Schlemm canal', 'The uveoscleral route does not pass through Schlemm canal.', 'outflow-pathways-equated'],
  ], 'variable-proportions'),
];
