export type CourseSummary = {
  id: string;
  code: string;
  title: string;
  description: string;
  lecturers: string[];
  moduleIds: string[];
  tone: string;
  coverImage: { src: string; width: number; height: number };
};

type Pair = [term: string, definition: string];

const concepts = (section: string, pairs: Pair[]) =>
  pairs.flatMap(([term, definition]) => [
    {
      section,
      group: 'definition',
      q: `Which description best matches ${term}?`,
      a: definition,
    },
    {
      section,
      group: 'term',
      q: `Which term is described as: ${definition}?`,
      a: term,
    },
  ]);

const figure = (
  src: string,
  width: number,
  height: number,
  alt: string,
  caption: string,
  credit: string,
) => ({ src, width, height, alt, caption, credit });

export const courses: CourseSummary[] = [
  {
    id: 'environmental-vision',
    code: 'OPT 508',
    title: 'Environmental Vision',
    description: 'Light, visual task analysis, ergonomics, ocular hazards, protection and workplace illumination.',
    lecturers: ['Dr David Ben Kumah'],
    moduleIds: ['environmental-vision'],
    tone: 'teal',
    coverImage: { src: '/images/courses/environmental/physical-optics.webp', width: 1263, height: 735 },
  },
  {
    id: 'human-visual-perception',
    code: 'OPT 374',
    title: 'Human Visual Perception',
    description: 'From sensation and retinal coding to the LGN, visual cortex and higher perceptual streams.',
    lecturers: ['Emmanuel Owusu, OD, MSc, M.Optom, PhD'],
    moduleIds: ['human-visual-perception'],
    tone: 'blue',
    coverImage: { src: '/images/courses/visual-perception/foundations.webp', width: 1400, height: 788 },
  },
  {
    id: 'neuro-anatomy',
    code: 'OPT 376',
    title: 'Neuro Anatomy & Ocular Anatomy',
    description: 'Nervous and supporting tissues, ocular adnexa, transparent media and ocular circulation.',
    lecturers: ['Clement Afari, OD, MOptom, PhD', 'Chris Hudson, PhD, MCOptom, FAAO', 'Additional supplied course decks'],
    moduleIds: ['tissue-foundations', 'ocular-adnexa', 'aqueous-vitreous', 'blood-supply'],
    tone: 'coral',
    coverImage: { src: '/images/courses/neuro-tissues/nervous-tissue.webp', width: 1400, height: 788 },
  },
  {
    id: 'pharmacology',
    code: 'OPT III',
    title: 'Ocular Pharmacology',
    description: 'Autonomic foundations and the adrenergic and cholinergic medicines most relevant to eye care.',
    lecturers: ['Newman Osafo, BPharm, PhD', 'Prof Priscilla K. Mante'],
    moduleIds: ['autonomic-pharmacology'],
    tone: 'violet',
    coverImage: { src: '/images/courses/pharmacology/cholinergic.webp', width: 1400, height: 788 },
  },
  {
    id: 'systemic-pathology',
    code: 'PATHOLOGY',
    title: 'Systemic Pathology',
    description: 'High-yield breast, cardiovascular, gastrointestinal, lymphoid, renal and respiratory pathology.',
    lecturers: ['Dr Bernard Petershie', 'Dr Mataji Arthur', 'Additional supplied course decks'],
    moduleIds: ['systemic-pathology'],
    tone: 'gold',
    coverImage: { src: '/images/courses/systemic-pathology/cardiovascular.webp', width: 1400, height: 802 },
  },
];

export const additionalModules = [
  {
    id: 'environmental-vision',
    courseId: 'environmental-vision',
    number: '01',
    shortTitle: 'Environmental Vision',
    title: 'Environmental Vision',
    tone: 'teal',
    lecturer: 'Dr David Ben Kumah',
    sourceNote: 'Rewritten from the supplied OPT 508/Environmental Vision lecture decks.',
    description: 'Physical optics, visual task analysis, workplace ergonomics, eye hazards, protection and lighting.',
    coverImage: { src: '/images/courses/environmental/physical-optics.webp', width: 1263, height: 735 },
    objectives: [
      'Relate optical radiation and visual conditions to performance and ocular safety.',
      'Analyse a work task using distance, detail, contrast, time, lighting and hazard information.',
      'Select ergonomic and protective controls that match the identified risk.',
    ],
    sections: [
      {
        id: 'env-optics',
        title: 'Physical optics & visual function',
        summary: 'Visible light is the part of optical radiation that stimulates photoreceptors. Wavelength, energy, diffraction, interference and polarisation help explain both visual performance and ocular exposure.',
        bullets: [
          'Optical radiation includes ultraviolet, visible and infrared wavebands; shorter wavelengths carry more photon energy.',
          'The cornea, lens and retina absorb different parts of the spectrum, so the tissue at risk depends on wavelength.',
          'Small apertures increase diffraction, while large pupils expose more optical aberration.',
        ],
        terms: ['Visible spectrum — approximately 400–780 nm', 'Diffraction — bending and spreading around an aperture', 'Polarisation — restriction of vibration to a plane'],
        clinical: 'Polarised filters reduce horizontally reflected glare, while UV-filtering lenses reduce short-wavelength exposure.',
        image: figure('/images/courses/environmental/physical-optics.webp', 1263, 735, 'Lecture diagram of the electromagnetic spectrum and optical radiation bands.', 'Optical radiation within the electromagnetic spectrum.', 'Supplied Environmental Vision lecture deck'),
      },
      {
        id: 'env-task',
        title: 'Visual task analysis',
        summary: 'A visual task analysis matches the worker, job and environment by identifying the critical detail, viewing conditions, visual demand and hazards before screening or intervention.',
        bullets: [
          'Survey the actual workspace and speak with the worker and supervisor.',
          'Record task size, working distance, contrast, illumination, glare, viewing time and movement.',
          'Separate visual ability requirements from correctable environmental barriers.',
        ],
        terms: ['Critical detail — smallest feature needed to do the task', 'Working distance — eye-to-task distance', 'Static acuity — resolution for a stationary target'],
        clinical: 'A prescription alone may not solve poor performance when contrast, glare or task layout is the main limitation.',
        image: figure('/images/courses/environmental/visual-task-analysis.webp', 1199, 762, 'Lecture slide listing the principal factors that influence visibility of a work task.', 'Factors that determine task visibility.', 'Supplied Visual Task Analysis lecture deck'),
      },
      {
        id: 'env-ergonomics',
        title: 'Visual ergonomics',
        summary: 'Visual ergonomics adapts the workstation to the user. Viewing distance, gaze angle, monitor tilt, document placement, posture and reflections interact rather than acting alone.',
        bullets: [
          'A screen distance of at least about 25 inches reduces accommodative and convergence demand for many users.',
          'Placing the display below eye level can reduce exposed ocular surface and support a comfortable gaze.',
          'Encourage position changes because prolonged fixed posture increases visual and musculoskeletal discomfort.',
        ],
        terms: ['Ergonomics — fitting work to human capabilities', 'Gaze angle — direction of viewing relative to straight ahead', 'Visual fatigue — discomfort after sustained visual demand'],
        clinical: 'Lower screen placement and scheduled breaks can help patients with computer-associated dryness and eyestrain.',
        image: figure('/images/courses/environmental/visual-ergonomics.webp', 1400, 640, 'Lecture diagram showing recommended monitor distance, vertical location and lighting considerations.', 'Core monitor-placement and lighting guidance.', 'Supplied Visual Ergonomics lecture deck'),
      },
      {
        id: 'env-hazards',
        title: 'Ocular hazards & injury patterns',
        summary: 'Workplace hazards may be mechanical or non-mechanical. Impact, penetration, chemicals, radiation, heat and electricity produce distinct injury patterns and require different first responses.',
        bullets: [
          'Mechanical hazards include blunt impact, flying particles and penetrating or perforating injuries.',
          'Alkalis penetrate rapidly and generally cause more severe chemical injury than acids.',
          'UV, visible and infrared radiation are absorbed at different ocular depths.',
        ],
        terms: ['Hazard — source with potential to cause harm', 'Penetrating injury — single full-thickness entry wound', 'Perforating injury — full-thickness entry and exit wounds'],
        clinical: 'Chemical exposure requires immediate copious irrigation; treatment should not wait for a complete history.',
        image: figure('/images/courses/environmental/eye-hazards.webp', 1400, 624, 'Lecture classification of mechanical and non-mechanical ocular hazards.', 'Classification of common ocular hazards.', 'Supplied Eye Hazards lecture deck'),
      },
      {
        id: 'env-protection',
        title: 'Eye & face protection',
        summary: 'Protection is selected after a hazard assessment. Spectacles, goggles, face shields, welding helmets and filter lenses differ in coverage and should be matched to impact, splash, dust, heat or radiation risk.',
        bullets: [
          'Engineering and administrative controls come before personal protective equipment where feasible.',
          'Goggles provide a seal; face shields protect a larger facial area but are usually secondary protection.',
          'Prescription-lens users still need compliant protective eyewear.',
        ],
        terms: ['Primary protector — eyewear worn directly over the eyes', 'Secondary protector — added face protection used with primary eyewear', 'Filter shade — optical density selected for a radiation source'],
        clinical: 'The right device is determined by the hazard, not by which protector is most convenient.',
        image: figure('/images/courses/environmental/eye-protection.webp', 1400, 779, 'Hazard-assessment table matching workplace hazards with sources and protective strategies.', 'Hazard assessment guides protective-equipment selection.', 'Supplied Eye and Face Protection lecture deck'),
      },
      {
        id: 'env-lighting',
        title: 'Workplace lighting',
        summary: 'Good lighting makes critical detail visible without excessive brightness, deep shadows or glare. Required illuminance rises as detail becomes smaller, contrast falls or speed and accuracy become more important.',
        bullets: [
          'Illuminance is measured in lux and describes light arriving at a surface.',
          'Direct systems send most light toward the task; indirect systems first reflect light from ceilings and walls.',
          'Control direct and reflected glare through fixture position, shielding, surface finishes and task lighting.',
        ],
        terms: ['Illuminance — luminous flux incident on a surface', 'Lux — one lumen per square metre', 'Glare — brightness that reduces comfort or visibility'],
        clinical: 'Older workers commonly need more task light but can also be more sensitive to glare, so simply increasing brightness is not enough.',
        image: figure('/images/courses/environmental/workplace-lighting.webp', 968, 406, 'Lecture diagrams comparing direct and indirect workplace lighting.', 'Direct and indirect lighting distribute light differently.', 'Supplied Workplace Lighting lecture deck'),
      },
    ],
    facts: [
      ...concepts('env-optics', [
        ['Visible radiation', 'Optical radiation of approximately 400–780 nm that stimulates vision'],
        ['Diffraction', 'Spreading of light when it passes an edge or small aperture'],
        ['Polarisation', 'Restriction of light vibration to a particular plane'],
        ['Resolving power', 'Ability of an optical system to form two discernible images from close points'],
      ]),
      ...concepts('env-task', [
        ['Visual task analysis', 'Systematic evaluation of a job’s visual demands and viewing conditions'],
        ['Critical detail', 'Smallest feature that must be resolved to perform a task'],
        ['Working distance', 'Distance from the observer’s eyes to the task'],
        ['Contrast', 'Difference in luminance or colour that makes an object distinguishable'],
      ]),
      ...concepts('env-ergonomics', [
        ['Ergonomics', 'Designing work and equipment to fit human capabilities'],
        ['Downward gaze', 'Viewing direction that can reduce exposed ocular surface during screen use'],
        ['Accommodation', 'Change in ocular focus needed for near viewing'],
        ['Visual fatigue', 'Eyestrain or discomfort associated with sustained visual demand'],
      ]),
      ...concepts('env-hazards', [
        ['Hazard', 'A potential source of harm'],
        ['Penetrating injury', 'A full-thickness ocular wound with an entry site only'],
        ['Perforating injury', 'A full-thickness ocular injury with entry and exit wounds'],
        ['Alkali burn', 'Chemical injury that rapidly penetrates ocular tissues and can be especially severe'],
      ]),
      ...concepts('env-protection', [
        ['Safety goggles', 'Primary protectors that can seal around the eyes against splash or dust'],
        ['Face shield', 'Secondary protector covering much of the face'],
        ['Filter lens', 'Protector selected to attenuate hazardous optical radiation'],
        ['Hazard assessment', 'Process of identifying exposures before selecting protective equipment'],
      ]),
      ...concepts('env-lighting', [
        ['Illuminance', 'Amount of luminous flux arriving at a surface'],
        ['Lux', 'SI unit equal to one lumen per square metre'],
        ['Direct glare', 'Bright source located directly in the field of view'],
        ['Indirect lighting', 'System sending most light to ceilings or walls before it reaches the task'],
        ['Task lighting', 'Local illumination directed at the work area'],
      ]),
    ],
  },
  {
    id: 'human-visual-perception',
    courseId: 'human-visual-perception',
    number: '01',
    shortTitle: 'Visual Perception',
    title: 'Human Visual Perception',
    tone: 'blue',
    lecturer: 'Emmanuel Owusu, OD, MSc, M.Optom, PhD',
    sourceNote: 'Rewritten from the supplied OPT 374 Human Visual Perception lecture decks.',
    description: 'Sensation and perception, retinal coding, the LGN and V1, and higher visual processing streams.',
    coverImage: { src: '/images/courses/visual-perception/foundations.webp', width: 1400, height: 788 },
    objectives: [
      'Distinguish sensory registration from perceptual interpretation.',
      'Trace visual information from photoreceptors through the retina, LGN and primary visual cortex.',
      'Relate higher visual streams to perception, action and characteristic cortical deficits.',
    ],
    sections: [
      {
        id: 'hvp-foundations',
        title: 'Sensation, perception & organisation',
        summary: 'Sensation detects physical stimulation; perception selects, organises and interprets it. Context, attention and prior knowledge help the brain turn retinal signals into meaningful objects and scenes.',
        bullets: [
          'The same sensory input may support more than one percept, as reversible figures demonstrate.',
          'Figure–ground organisation separates an object of attention from its background.',
          'Perception is an active inference, not a pixel-for-pixel copy of the retinal image.',
        ],
        terms: ['Sensation — detection and encoding of stimulation', 'Perception — meaningful interpretation of sensory signals', 'Figure–ground — separation of an object from its background'],
        clinical: 'A patient may have intact acuity yet struggle to recognise or attend to visual information because perception depends on cortical processing.',
        image: figure('/images/courses/visual-perception/foundations.webp', 1400, 788, 'Rubin vase reversible figure showing either a central vase or two facing profiles.', 'Rubin’s vase demonstrates figure–ground reversal.', 'Supplied Human Visual Perception lecture deck'),
      },
      {
        id: 'hvp-retina',
        title: 'Retinal coding',
        summary: 'The duplex retina uses rods and cones, bipolar cells, horizontal and amacrine cells, and ganglion cells to transform light into contrast-sensitive neural signals.',
        bullets: [
          'Rods are highly sensitive in dim light; cones support high acuity and colour vision.',
          'Convergence increases sensitivity but reduces spatial detail.',
          'Centre–surround receptive fields and lateral inhibition enhance local contrast.',
        ],
        terms: ['Phototransduction — conversion of light into an electrical response', 'Duplex retina — rod and cone subsystems', 'Lateral inhibition — neighbouring activity suppresses a response'],
        clinical: 'Dark adaptation has a rapid cone phase followed by a slower, more sensitive rod phase.',
        image: figure('/images/courses/visual-perception/retina.webp', 1400, 788, 'Lecture diagram of the duplex retina and rod and cone visual pathways.', 'The duplex retina separates rod- and cone-dominated processing.', 'Supplied Human Visual Perception lecture deck'),
      },
      {
        id: 'hvp-lgn',
        title: 'LGN & primary visual cortex',
        summary: 'Retinal ganglion-cell axons relay through organised layers of the lateral geniculate nucleus before reaching retinotopically organised primary visual cortex.',
        bullets: [
          'Nasal retinal fibres cross at the optic chiasm; temporal retinal fibres remain uncrossed.',
          'Magnocellular pathways emphasise motion and temporal change, while parvocellular pathways emphasise fine detail and colour.',
          'V1 neurons show orientation selectivity and combine signals from the two eyes.',
        ],
        terms: ['LGN — thalamic relay nucleus for the main visual pathway', 'Retinotopy — orderly spatial map of the retina', 'Orientation selectivity — preference for edges at a particular angle'],
        clinical: 'Damage behind the chiasm produces visual-field loss that respects the vertical meridian.',
        image: figure('/images/courses/visual-perception/lgn-cortex.webp', 1400, 788, 'Lecture comparison table of magnocellular, parvocellular and koniocellular pathways.', 'Major LGN pathways differ in size, speed, colour and spatial detail.', 'Supplied Human Visual Perception lecture deck'),
      },
      {
        id: 'hvp-extrastriate',
        title: 'Extrastriate processing',
        summary: 'Beyond V1, distributed cortical areas analyse increasingly complex attributes. The ventral stream supports object identity, while the dorsal stream supports spatial guidance and action.',
        bullets: [
          'The ventral “what” stream projects mainly toward temporal cortex.',
          'The dorsal “where/how” stream projects mainly toward parietal cortex.',
          'Selective lesions can impair motion perception, face recognition or spatial attention.',
        ],
        terms: ['Ventral stream — object and form processing pathway', 'Dorsal stream — spatial and visually guided action pathway', 'Prosopagnosia — impaired face recognition'],
        clinical: 'Akinetopsia, hemispatial neglect and prosopagnosia illustrate that different perceptual functions can fail independently.',
        image: figure('/images/courses/visual-perception/extrastriate.webp', 1400, 788, 'Lecture diagram of dorsal where and ventral what visual-processing streams.', 'The two-stream model of higher visual processing.', 'Supplied Human Visual Perception lecture deck'),
      },
    ],
    facts: [
      ...concepts('hvp-foundations', [
        ['Sensation', 'Detection and neural encoding of physical stimulation'],
        ['Perception', 'Selection, organisation and interpretation of sensory information'],
        ['Figure–ground organisation', 'Separation of a focal object from its background'],
        ['Reversible figure', 'Image that supports alternating valid perceptual interpretations'],
        ['Attention', 'Selective allocation of processing resources to information'],
        ['Top-down processing', 'Interpretation influenced by expectation, knowledge and context'],
      ]),
      ...concepts('hvp-retina', [
        ['Phototransduction', 'Conversion of absorbed light into an electrical response'],
        ['Rod', 'Photoreceptor specialised for high sensitivity in dim illumination'],
        ['Cone', 'Photoreceptor supporting colour and high spatial acuity'],
        ['Lateral inhibition', 'Suppression from neighbouring pathways that enhances contrast'],
        ['Receptive field', 'Region of visual space in which stimulation changes a neuron’s response'],
        ['Dark adaptation', 'Recovery of visual sensitivity after moving into darkness'],
        ['Retinal ganglion cell', 'Output neuron whose axon forms the optic nerve'],
      ]),
      ...concepts('hvp-lgn', [
        ['Lateral geniculate nucleus', 'Layered thalamic relay for the retinogeniculocortical pathway'],
        ['Optic chiasm', 'Site where nasal retinal fibres cross'],
        ['Magnocellular pathway', 'Fast pathway emphasising motion and temporal change'],
        ['Parvocellular pathway', 'Pathway emphasising fine spatial detail and red–green colour'],
        ['Retinotopy', 'Orderly mapping of neighbouring retinal locations in the brain'],
        ['Orientation selectivity', 'Preference of a cortical neuron for an edge at a particular angle'],
      ]),
      ...concepts('hvp-extrastriate', [
        ['Ventral stream', 'Temporal-cortex pathway supporting object identity'],
        ['Dorsal stream', 'Parietal-cortex pathway supporting spatial action'],
        ['Prosopagnosia', 'Selective difficulty recognising familiar faces'],
        ['Akinetopsia', 'Selective impairment of motion perception'],
        ['Hemispatial neglect', 'Failure to attend to one side of space despite adequate sensation'],
        ['Extrastriate cortex', 'Visual cortical areas beyond primary visual cortex'],
      ]),
    ],
  },
  {
    id: 'tissue-foundations',
    courseId: 'neuro-anatomy',
    number: '01',
    shortTitle: 'Tissue Foundations',
    title: 'Tissue Foundations for Neuro Anatomy',
    tone: 'coral',
    lecturer: 'Lecturer not identified in the supplied tissue decks',
    sourceNote: 'Rewritten from the supplied nervous-tissue, connective-tissue and epithelium decks.',
    description: 'Neurons and glia, connective-tissue organisation, and epithelial structure and classification.',
    coverImage: { src: '/images/courses/neuro-tissues/nervous-tissue.webp', width: 1400, height: 788 },
    objectives: [
      'Relate neuronal structure and neuroglial roles to signalling and repair.',
      'Recognise the cells, fibres and matrix that define connective tissues.',
      'Classify epithelia by layers and cell shape and connect structure with function.',
    ],
    sections: [
      {
        id: 'tissue-nervous',
        title: 'Nervous tissue',
        summary: 'Nervous tissue contains excitable neurons and supporting neuroglia. Neuronal polarity allows dendrites to receive information, the soma to integrate it and the axon to transmit it.',
        bullets: [
          'The CNS comprises brain and spinal cord; nerves and ganglia form the PNS.',
          'Synapses transmit information chemically or electrically between cells.',
          'CNS repair is limited, while peripheral axons can regenerate when the cell body and guidance pathway survive.',
        ],
        terms: ['Soma — metabolic centre of a neuron', 'Axon — process carrying impulses away from the soma', 'Neuroglia — non-neuronal supporting cells'],
        clinical: 'Demyelination slows or blocks conduction because myelin enables rapid saltatory propagation.',
        image: figure('/images/courses/neuro-tissues/nervous-tissue.webp', 1400, 788, 'Lecture slide distinguishing excitable neurons from supporting neuroglia.', 'The two broad cell classes of nervous tissue.', 'Supplied Nervous Tissue lecture deck'),
      },
      {
        id: 'tissue-connective',
        title: 'Connective tissue',
        summary: 'Connective tissue is defined by cells dispersed in an extracellular matrix containing ground substance and collagen, elastic or reticular fibres.',
        bullets: [
          'Fibroblasts are major matrix-producing resident cells.',
          'Collagen resists tension, elastic fibres permit recoil and reticular fibres form delicate support networks.',
          'Loose and dense connective tissues differ in fibre packing and mechanical role.',
        ],
        terms: ['Extracellular matrix — ground substance plus fibres', 'Fibroblast — principal matrix-producing cell', 'Collagen — tensile structural protein'],
        clinical: 'Vitamin C deficiency weakens collagen synthesis and can impair wound healing.',
        image: figure('/images/courses/neuro-tissues/connective-tissue.webp', 1400, 788, 'Lecture diagram dividing connective tissue into cells and extracellular matrix.', 'Core components of connective tissue.', 'Supplied Connective Tissue lecture deck'),
      },
      {
        id: 'tissue-epithelium',
        title: 'Epithelium & tissue integration',
        summary: 'Epithelia cover surfaces, line cavities and form glands. They are highly cellular, polar, attached to a basement membrane and classified by layer number and apical cell shape.',
        bullets: [
          'Simple epithelia favour diffusion, absorption and secretion; stratified epithelia favour protection.',
          'Apical, lateral and basal domains have distinct structures and functions.',
          'Epithelia are avascular and depend on diffusion from underlying connective tissue.',
        ],
        terms: ['Cell polarity — structural distinction between apical and basal domains', 'Basement membrane — interface supporting epithelium', 'Simple epithelium — one cell layer'],
        clinical: 'Metaplasia is an adaptive replacement of one mature cell type by another and may increase later dysplasia risk.',
        image: figure('/images/courses/neuro-tissues/epithelium.webp', 1400, 788, 'Lecture classification of simple and stratified epithelia by layers and cell shape.', 'Epithelial classification uses cell layers and apical shape.', 'Supplied Epithelium lecture deck'),
      },
    ],
    facts: [
      ...concepts('tissue-nervous', [
        ['Neuron', 'Excitable cell specialised to receive and transmit signals'],
        ['Soma', 'Metabolic and integrative centre containing the nucleus'],
        ['Dendrite', 'Neuronal process specialised mainly to receive input'],
        ['Axon', 'Neuronal process conducting impulses away from the cell body'],
        ['Synapse', 'Specialised junction for communication between cells'],
        ['Myelin', 'Insulating sheath that increases conduction speed'],
        ['Astrocyte', 'CNS glial cell supporting neurons and the neural environment'],
        ['Schwann cell', 'PNS glial cell that forms myelin around axons'],
        ['Saltatory conduction', 'Impulse propagation by jumping between nodes of Ranvier'],
      ]),
      ...concepts('tissue-connective', [
        ['Extracellular matrix', 'Ground substance and fibres surrounding connective-tissue cells'],
        ['Fibroblast', 'Resident cell that synthesises fibres and ground substance'],
        ['Collagen fibre', 'Matrix fibre providing high tensile strength'],
        ['Elastic fibre', 'Matrix fibre allowing stretch and recoil'],
        ['Reticular fibre', 'Fine type III collagen fibre forming supportive networks'],
        ['Loose connective tissue', 'Tissue with abundant ground substance and relatively loose fibres'],
        ['Dense regular connective tissue', 'Parallel collagen bundles adapted to unidirectional tension'],
        ['Macrophage', 'Phagocytic connective-tissue cell derived from monocytes'],
      ]),
      ...concepts('tissue-epithelium', [
        ['Epithelium', 'Highly cellular tissue covering surfaces, lining cavities and forming glands'],
        ['Basement membrane', 'Supportive interface between epithelium and connective tissue'],
        ['Simple epithelium', 'Epithelium consisting of one cell layer'],
        ['Stratified epithelium', 'Epithelium containing two or more cell layers'],
        ['Squamous cell', 'Flat cell that is wider than it is tall'],
        ['Goblet cell', 'Unicellular mucus-secreting epithelial gland'],
        ['Cell polarity', 'Organisation into distinct apical, lateral and basal domains'],
        ['Metaplasia', 'Reversible replacement of one mature cell type by another'],
      ]),
    ],
  },
  {
    id: 'autonomic-pharmacology',
    courseId: 'pharmacology',
    number: '01',
    shortTitle: 'Autonomic Pharmacology',
    title: 'Adrenergic & Cholinergic Pharmacology',
    tone: 'violet',
    lecturer: 'Newman Osafo, BPharm, PhD · Prof Priscilla K. Mante',
    sourceNote: 'Rewritten from the supplied Adrenergic Pharmacology PDF and Cholinergic Pharmacology deck.',
    description: 'Autonomic transmission, receptor families, agonists, antagonists and common ocular applications.',
    coverImage: { src: '/images/courses/pharmacology/cholinergic.webp', width: 1400, height: 788 },
    objectives: [
      'Map autonomic neurotransmitters and receptor families to organ responses.',
      'Explain how agonists, antagonists and enzyme inhibitors modify transmission.',
      'Apply adrenergic and cholinergic mechanisms to pupil, accommodation and glaucoma therapy.',
    ],
    sections: [
      {
        id: 'pharm-adrenergic',
        title: 'Adrenergic pharmacology',
        summary: 'Adrenergic transmission uses noradrenaline at most sympathetic neuroeffector junctions. Catecholamine synthesis, vesicular storage, release, reuptake and metabolism create multiple drug targets.',
        bullets: [
          'Tyrosine hydroxylase is the rate-limiting step in catecholamine synthesis.',
          'Alpha-1 activation contracts radial iris muscle and causes mydriasis without cycloplegia.',
          'Alpha-2 agonists such as brimonidine lower intraocular pressure by reducing aqueous production and increasing uveoscleral outflow.',
        ],
        terms: ['Sympathomimetic — drug producing adrenergic effects', 'Alpha-1 receptor — receptor mediating smooth-muscle contraction', 'Beta blocker — antagonist at beta-adrenoceptors'],
        clinical: 'Topical beta blockers reduce aqueous production but require caution in asthma, bradycardia and conduction disease.',
        image: figure('/images/courses/pharmacology/adrenergic.webp', 576, 432, 'Adrenergic lecture figure showing the catecholamine synthesis pathway from tyrosine to noradrenaline.', 'Catecholamine synthesis provides several pharmacological targets.', 'Supplied Adrenergic Pharmacology PDF'),
      },
      {
        id: 'pharm-cholinergic',
        title: 'Cholinergic pharmacology',
        summary: 'Acetylcholine acts at muscarinic and nicotinic receptors. Direct agonists activate receptors, cholinesterase inhibitors prolong acetylcholine action and antagonists block receptor responses.',
        bullets: [
          'All autonomic preganglionic fibres and parasympathetic postganglionic fibres release acetylcholine.',
          'Muscarinic activation contracts the iris sphincter and ciliary muscle, producing miosis and accommodation.',
          'Atropine blocks muscarinic receptors, producing mydriasis and cycloplegia.',
        ],
        terms: ['Cholinomimetic — drug that increases cholinergic activity', 'Muscarinic receptor — G-protein-coupled acetylcholine receptor', 'Cholinesterase inhibitor — drug slowing acetylcholine breakdown'],
        clinical: 'Pilocarpine can enhance trabecular outflow through ciliary-muscle contraction but may cause brow ache and induced myopia.',
        image: figure('/images/courses/pharmacology/cholinergic.webp', 1400, 788, 'Lecture diagram mapping autonomic neurotransmitters and receptors at preganglionic and postganglionic synapses.', 'Acetylcholine is used by all autonomic preganglionic fibres.', 'Supplied Cholinergic Pharmacology lecture deck'),
      },
    ],
    facts: [
      ...concepts('pharm-adrenergic', [
        ['Noradrenaline', 'Principal transmitter at most sympathetic postganglionic neuroeffector junctions'],
        ['Tyrosine hydroxylase', 'Rate-limiting enzyme in catecholamine synthesis'],
        ['VMAT', 'Vesicular transporter that stores monoamines inside synaptic vesicles'],
        ['NET', 'Neuronal transporter responsible for much noradrenaline reuptake'],
        ['Monoamine oxidase', 'Intraneuronal enzyme that metabolises monoamines'],
        ['Alpha-1 receptor', 'Adrenoceptor commonly producing smooth-muscle contraction'],
        ['Alpha-2 agonist', 'Drug class that can reduce aqueous production and enhance uveoscleral outflow'],
        ['Beta-1 receptor', 'Adrenoceptor strongly associated with increased cardiac rate and force'],
        ['Phenylephrine', 'Direct alpha-1 agonist used to produce mydriasis'],
        ['Brimonidine', 'Relatively selective alpha-2 agonist used to lower intraocular pressure'],
        ['Timolol', 'Non-selective beta blocker that reduces aqueous production'],
        ['Sympathomimetic', 'Drug that directly or indirectly increases adrenergic effects'],
        ['Sympatholytic', 'Drug that reduces adrenergic transmission or responses'],
      ]),
      ...concepts('pharm-cholinergic', [
        ['Acetylcholine', 'Transmitter released by all autonomic preganglionic fibres'],
        ['Muscarinic receptor', 'G-protein-coupled receptor activated by acetylcholine'],
        ['Nicotinic receptor', 'Ligand-gated ion channel activated by acetylcholine'],
        ['Acetylcholinesterase', 'Enzyme rapidly hydrolysing acetylcholine in synapses'],
        ['Pilocarpine', 'Direct muscarinic agonist that causes miosis and ciliary-muscle contraction'],
        ['Atropine', 'Competitive muscarinic antagonist producing mydriasis and cycloplegia'],
        ['Cholinomimetic', 'Drug that reproduces or increases acetylcholine effects'],
        ['Cholinesterase inhibitor', 'Drug that prolongs acetylcholine action by inhibiting breakdown'],
        ['Miosis', 'Constriction of the pupil'],
        ['Cycloplegia', 'Paralysis of accommodation'],
        ['Parasympathetic postganglionic fibre', 'Autonomic fibre that normally releases acetylcholine at its effector'],
        ['Organophosphate', 'Often irreversible cholinesterase inhibitor capable of causing cholinergic toxicity'],
      ]),
    ],
  },
  {
    id: 'systemic-pathology',
    courseId: 'systemic-pathology',
    number: '01',
    shortTitle: 'Systemic Pathology',
    title: 'Systemic Pathology Review',
    tone: 'gold',
    lecturer: 'Dr Bernard Petershie · Dr Mataji Arthur · additional supplied decks',
    sourceNote: 'Rewritten from the six supplied systemic-pathology lecture decks.',
    description: 'Organised review of breast, cardiovascular, gastrointestinal, lymphoid, renal and respiratory disease.',
    coverImage: { src: '/images/courses/systemic-pathology/cardiovascular.webp', width: 1400, height: 802 },
    objectives: [
      'Recognise characteristic mechanisms and morphology across six organ systems.',
      'Connect common clinical presentations with their underlying pathology.',
      'Compare high-yield inflammatory, vascular, obstructive and neoplastic disorders.',
    ],
    sections: [
      {
        id: 'path-breast',
        title: 'Breast pathology',
        summary: 'Breast disease is best understood from the terminal duct lobular unit, hormonal responsiveness and the distinction between inflammatory, benign proliferative and malignant processes.',
        bullets: [
          'The terminal duct lobular unit is the functional unit and origin of many lesions.',
          'A mobile circumscribed mass in a young patient suggests fibroadenoma, whereas invasive carcinoma is often hard and irregular.',
          'The upper outer quadrant contains much breast tissue and is a common site of carcinoma.',
        ],
        terms: ['TDLU — terminal duct lobular unit', 'Carcinoma in situ — malignant epithelial cells confined by basement membrane', 'Peau d’orange — skin oedema from lymphatic obstruction'],
        clinical: 'A breast mass is assessed using age, examination and appropriate imaging or tissue sampling rather than one feature alone.',
        image: figure('/images/courses/systemic-pathology/breast.webp', 1400, 856, 'Lecture microanatomy diagram of breast ducts, lobules and epithelial lining.', 'Breast microanatomy and the terminal duct–lobular system.', 'Supplied Breast Pathology lecture deck'),
      },
      {
        id: 'path-cardio',
        title: 'Cardiovascular pathology',
        summary: 'Cardiovascular disease reflects pump failure, abnormal flow, pressure overload, ischaemia and vessel-wall injury. Consequences differ between left- and right-sided failure.',
        bullets: [
          'Left-sided failure commonly produces pulmonary congestion and oedema.',
          'Right-sided failure produces systemic venous congestion, dependent oedema and congestive hepatomegaly.',
          'Atherosclerosis involves intimal plaques and can cause thrombosis, aneurysm or organ ischaemia.',
        ],
        terms: ['Heart failure — inability to maintain adequate circulation', 'Atherosclerosis — intimal fibrofatty plaque disease', 'Infarction — ischaemic necrosis'],
        clinical: 'Hypertension accelerates vascular injury and produces target-organ damage in the heart, brain, kidneys and retina.',
        image: figure('/images/courses/systemic-pathology/cardiovascular.webp', 1400, 802, 'Lecture diagrams of the cardiac conduction system and coronary arteries.', 'Conduction pathways and coronary arterial supply.', 'Supplied Cardiovascular Pathology lecture deck'),
      },
      {
        id: 'path-gi',
        title: 'Gastrointestinal pathology',
        summary: 'Gastrointestinal pathology spans mucosal injury, motility disorders, malabsorption, inflammation, obstruction and neoplasia from the oral cavity to the colon.',
        bullets: [
          'GERD results from reduced lower-oesophageal sphincter competence and may lead to Barrett metaplasia.',
          'Peptic ulcers may bleed, perforate or obstruct.',
          'Inflammatory bowel disease includes Crohn disease and ulcerative colitis with different distributions and complications.',
        ],
        terms: ['Barrett oesophagus — intestinal metaplasia of distal oesophagus', 'Steatorrhoea — excess fat in stool', 'Diverticulum — outpouching from the alimentary tract'],
        clinical: 'Progressive dysphagia from solids to liquids raises concern for mechanical obstruction such as oesophageal carcinoma.',
        image: figure('/images/courses/systemic-pathology/gastrointestinal.webp', 1400, 753, 'Lecture illustration of dilated submucosal oesophageal varices.', 'Oesophageal varices arise in portal hypertension.', 'Supplied Gastrointestinal Pathology lecture deck'),
      },
      {
        id: 'path-lymph',
        title: 'Lymphoreticular pathology',
        summary: 'Lymphoid organs organise immune-cell production and activation. Reactive lymphadenitis must be distinguished from lymphoid neoplasms using architecture, cell type and clinical context.',
        bullets: [
          'Lymph-node cortex is B-cell rich, paracortex is T-cell rich and medulla contains cords and sinuses.',
          'The spleen filters blood; white pulp is lymphoid and red pulp removes aged red cells.',
          'Hodgkin lymphoma features neoplastic Reed–Sternberg cells in a larger reactive background.',
        ],
        terms: ['Lymphadenopathy — enlarged lymph node', 'Reed–Sternberg cell — characteristic giant cell of Hodgkin lymphoma', 'Starry-sky pattern — macrophages among tumour cells'],
        clinical: 'Persistent painless lymphadenopathy, constitutional symptoms or abnormal blood counts require systematic evaluation.',
        image: figure('/images/courses/systemic-pathology/lymphoreticular.webp', 1400, 655, 'Lecture diagram of normal lymph-node cortex, paracortex, medulla and lymphatic flow.', 'Normal lymph-node architecture.', 'Supplied Lymphoreticular Pathology lecture deck'),
      },
      {
        id: 'path-renal',
        title: 'Renal pathology',
        summary: 'Renal disease is organised by the nephron compartment involved: glomeruli, tubules, interstitium, vessels or urinary outflow. Each produces characteristic clinical syndromes.',
        bullets: [
          'The filtration barrier consists of fenestrated endothelium, glomerular basement membrane and podocyte slit diaphragms.',
          'Nephritic syndrome reflects inflammatory glomerular injury; nephrotic syndrome reflects marked permeability to protein.',
          'Acute tubular injury is a common cause of acute kidney injury.',
        ],
        terms: ['Azotaemia — raised nitrogenous waste products in blood', 'Nephrotic syndrome — heavy proteinuria with hypoalbuminaemia and oedema', 'Nephritic syndrome — haematuria with inflammatory glomerular dysfunction'],
        clinical: 'Oedema, hypertension, altered urine output and abnormal urinalysis help localise renal injury.',
        image: figure('/images/courses/systemic-pathology/renal.webp', 1400, 851, 'Lecture diagram of the nephron and its renal vascular supply.', 'Nephron segments and renal vasculature.', 'Supplied Renal Pathology lecture deck'),
      },
      {
        id: 'path-respiratory',
        title: 'Respiratory pathology',
        summary: 'Respiratory disease includes collapse, oedema, obstructive airway disorders, infection and malignancy. Patterns of airflow limitation and tissue destruction help distinguish disorders.',
        bullets: [
          'Emphysema is permanent air-space enlargement with wall destruction and little fibrosis.',
          'Chronic bronchitis is defined clinically by productive cough for at least three months in each of two consecutive years.',
          'Asthma causes variable, usually reversible airflow obstruction with airway inflammation.',
        ],
        terms: ['Atelectasis — incomplete expansion or collapse of lung', 'Emphysema — destructive enlargement distal to terminal bronchioles', 'Bronchiectasis — permanent dilation of bronchi from wall destruction'],
        clinical: 'Bacterial pneumonia may follow lobar or bronchopneumonic patterns and can complicate with abscess, empyema or sepsis.',
        image: figure('/images/courses/systemic-pathology/respiratory.webp', 1400, 709, 'Lecture diagrams classifying obstructive, compressive and contraction atelectasis.', 'Major mechanisms of secondary atelectasis.', 'Supplied Respiratory Pathology lecture deck'),
      },
    ],
    facts: [
      ...concepts('path-breast', [
        ['Terminal duct lobular unit', 'Functional breast unit and origin of many common lesions'],
        ['Fibroadenoma', 'Common benign mobile breast tumour in younger patients'],
        ['Carcinoma in situ', 'Malignant epithelial proliferation confined by basement membrane'],
        ['Peau d’orange', 'Dimpled skin caused by tumour obstruction of dermal lymphatics'],
      ]),
      ...concepts('path-cardio', [
        ['Left-sided heart failure', 'Pump failure commonly causing pulmonary congestion and oedema'],
        ['Right-sided heart failure', 'Pump failure commonly causing systemic venous congestion'],
        ['Atherosclerosis', 'Intimal fibrofatty plaque disease of medium and large arteries'],
        ['Infarction', 'Tissue necrosis caused by ischaemia'],
      ]),
      ...concepts('path-gi', [
        ['Barrett oesophagus', 'Intestinal metaplasia replacing distal oesophageal squamous epithelium'],
        ['Achalasia', 'Failure of the lower oesophageal sphincter to relax because inhibitory neurons are lost'],
        ['Steatorrhoea', 'Excess fat in stool due to malabsorption'],
        ['Diverticulum', 'Blind pouch communicating with the alimentary lumen'],
      ]),
      ...concepts('path-lymph', [
        ['Lymphadenopathy', 'Enlargement of one or more lymph nodes'],
        ['Reed–Sternberg cell', 'Characteristic giant neoplastic cell of classical Hodgkin lymphoma'],
        ['White pulp', 'Splenic lymphoid tissue organised around arteries'],
        ['Starry-sky pattern', 'Pale macrophages scattered among densely packed tumour cells'],
      ]),
      ...concepts('path-renal', [
        ['Nephron', 'Functional unit of the kidney'],
        ['Azotaemia', 'Elevation of nitrogenous waste products in blood'],
        ['Nephrotic syndrome', 'Heavy proteinuria with hypoalbuminaemia, oedema and hyperlipidaemia'],
        ['Nephritic syndrome', 'Inflammatory glomerular syndrome with haematuria and reduced filtration'],
      ]),
      ...concepts('path-respiratory', [
        ['Atelectasis', 'Incomplete expansion or collapse of lung tissue'],
        ['Emphysema', 'Permanent enlargement of distal air spaces with wall destruction'],
        ['Chronic bronchitis', 'Productive cough for at least three months in each of two consecutive years'],
        ['Asthma', 'Inflammatory disease with variable expiratory airflow obstruction'],
        ['Bronchiectasis', 'Permanent dilation of bronchi following wall destruction'],
      ]),
    ],
  },
];
