import type { Figure } from '@/lib/legacy/types';

const COURSE_CREDIT = 'Supplied OPT 376 lecture deck';
const NEI_EYE_URL = 'https://www.nei.nih.gov/eye-health-information/healthy-vision/nei-for-kids/about-eye';
const OPENSTAX_EYE_URL = 'https://openstax.org/books/biology-2e/pages/36-5-vision';

export const sectionImages: Record<string, Figure> = {
  landmarks: { src: '/images/modules/ocular/01-landmarks.webp', width: 1600, height: 601, alt: 'Labelled front and side views of the eyelids showing the palpebral aperture, canthi, puncta, limbus and upper and lower lids.', caption: 'External eyelid landmarks and palpebral topography.', credit: COURSE_CREDIT },
  muscles: { src: '/images/modules/ocular/02-eyelid-layers.webp', width: 625, height: 614, alt: 'Histological cross-section of an eyelid labelled with skin, orbicularis oculi, hair follicle, meibomian glands, conjunctiva and cornea.', caption: 'Cross-section showing the principal layers of the eyelid.', credit: COURSE_CREDIT },
  'tarsus-glands': { src: '/images/modules/ocular/03-tarsus-conjunctiva.webp', width: 356, height: 245, alt: 'Diagram of upper and lower tarsal plates showing rows of meibomian glands, their duct openings, puncta and palpebral conjunctiva.', caption: 'Meibomian glands within the upper and lower tarsal plates.', credit: COURSE_CREDIT },
  'lower-lid-blood': { src: '/images/modules/ocular/04-eyelid-blood-supply.webp', width: 1024, height: 546, alt: 'Diagram of ophthalmic and facial venous connections around the orbit, including the superior and inferior ophthalmic veins, lacrimal vein and vortex veins.', caption: 'Orbital venous connections relevant to the lids and conjunctiva.', credit: COURSE_CREDIT },
  'lacrimal-gland': { src: '/images/modules/ocular/05-lacrimal-gland.webp', width: 930, height: 889, alt: 'Anatomical illustration locating the lacrimal gland in the superolateral orbit above the outer part of the upper eyelid.', caption: 'Position of the lacrimal gland in the superolateral orbit.', credit: COURSE_CREDIT },
  tears: { src: '/images/modules/ocular/06-tear-film-drainage.webp', width: 388, height: 254, alt: 'Tear drainage diagram tracing tears from the lacrimal gland across the eye into the puncta, canaliculi, lacrimal sac and nasolacrimal duct.', caption: 'Tear drainage from the lacrimal gland to the nasal cavity.', credit: COURSE_CREDIT },
  'media-chambers': { src: '/images/modules/aqueous/01-media-chambers.webp', width: 1043, height: 577, alt: 'OpenStax cross-section of the human eye labelling the aqueous humour at the front and vitreous humour in the large posterior cavity.', caption: 'The transparent media and their positions within the globe.', credit: 'OpenStax Biology 2e · CC BY-NC-SA', sourceUrl: OPENSTAX_EYE_URL },
  production: { src: '/images/modules/aqueous/02-aqueous-production.webp', width: 833, height: 1200, alt: 'National Eye Institute eye cross-section focused on the cornea, iris, pupil and lens of the anterior segment.', caption: 'Anterior-segment relationships around the site of aqueous production.', credit: 'National Eye Institute', sourceUrl: NEI_EYE_URL },
  flow: { src: '/images/modules/aqueous/03-aqueous-flow.webp', width: 458, height: 577, alt: 'OpenStax anterior eye cross-section showing the cornea, iris, pupil, lens and aqueous humour between the cornea and iris.', caption: 'Aqueous passes from the posterior chamber through the pupil into the anterior chamber.', credit: 'OpenStax Biology 2e · CC BY-NC-SA', sourceUrl: OPENSTAX_EYE_URL },
  iop: { src: '/images/modules/aqueous/04-iop-anterior-segment.webp', width: 1344, height: 1200, alt: 'National Eye Institute side-view eye diagram showing the cornea, iris, lens, retina, optic nerve and vitreous humour.', caption: 'Whole-eye orientation for the anterior chamber and intraocular pressure.', credit: 'National Eye Institute', sourceUrl: NEI_EYE_URL },
  'vitreous-anatomy': { src: '/images/modules/aqueous/05-vitreous-anatomy.webp', width: 1049, height: 1200, alt: 'National Eye Institute cross-section highlighting the vitreous humour filling the posterior cavity between the lens and retina.', caption: 'The vitreous body fills most of the posterior segment.', credit: 'National Eye Institute', sourceUrl: NEI_EYE_URL },
  'vitreous-clinical': { src: '/images/modules/aqueous/06-vitreous-clinical.webp', width: 625, height: 577, alt: 'OpenStax eye cross-section showing the vitreous humour in direct relation to the retina and optic nerve.', caption: 'Vitreous-retina relationships are clinically important when traction develops.', credit: 'OpenStax Biology 2e · CC BY-NC-SA', sourceUrl: OPENSTAX_EYE_URL },
  'arterial-origins': { src: '/images/modules/blood/01-arterial-origins.webp', width: 1198, height: 604, alt: 'Diagram of the major arteries from the aortic arch to the carotid arteries and cerebral circulation.', caption: 'Arterial origins leading to the internal carotid and ophthalmic arteries.', credit: COURSE_CREDIT },
  ciliary: { src: '/images/modules/blood/02-ciliary-choroidal.webp', width: 800, height: 593, alt: 'Cross-section of the posterior eye showing retinal vessels, long and short posterior ciliary arteries, choroidal vessels and a vortex vein.', caption: 'Retinal and ciliary circulation in the posterior globe.', credit: COURSE_CREDIT },
  retinal: { src: '/images/modules/blood/03-retinal-faz.webp', width: 800, height: 569, alt: 'Fluorescein angiogram of the retina showing branching retinal vessels and the dark foveal avascular zone at the centre.', caption: 'Retinal circulation around the foveal avascular zone.', credit: COURSE_CREDIT },
  barriers: { src: '/images/modules/blood/04-blood-ocular-barriers.webp', width: 800, height: 511, alt: 'Comparison diagrams of retinal and choroidal capillaries, showing continuous retinal endothelium and fenestrated choroidal endothelium.', caption: 'Continuous retinal capillaries compared with fenestrated choroidal capillaries.', credit: COURSE_CREDIT },
  microcirculation: { src: '/images/modules/blood/05-retinal-microcirculation.webp', width: 500, height: 650, alt: 'Microscopic view of a narrow retinal capillary labelled with endothelial cells and pericytes.', caption: 'Endothelial cells and pericytes in the retinal capillary wall.', credit: COURSE_CREDIT },
  'clinical-blood': { src: '/images/modules/blood/06-clinical-circumciliary.webp', width: 279, height: 181, alt: 'Clinical illustration of a red eye with a concentrated ring of redness around the corneal limbus.', caption: 'Circumciliary flush is deepest around the corneal limbus.', credit: COURSE_CREDIT },
};
