import type { Module } from '@/lib/legacy/types';

type Opt370ModuleInput = Omit<Module, 'sections'> & {
  sections: Array<Omit<Module['sections'][number], 'image'>>;
};

const cover = (moduleId: string) => ({
  src: `/images/courses/opt370/${moduleId}-cover.svg`,
  width: 1200,
  height: 675,
});

const sectionFigure = (moduleId: string, title: string) => ({
  ...cover(moduleId),
  alt: `Original illustrated cover for ${title}.`,
  caption: `${title} module overview.`,
  credit: 'Original OPT 370 course artwork',
});

const opt370ModuleInputs: Opt370ModuleInput[] = [
  {
    id: 'schematic-eye-refractive-states',
    courseId: 'dispensing-optics-ii',
    number: '01',
    shortTitle: 'Schematic Eye',
    title: 'Schematic Eye and Refractive States',
    tone: 'blue',
    sourceNote: 'Rewritten only from the supplied OPT 370 course materials; see source register and ambiguity log.',
    description: 'Vergence, Gullstrand and reduced-eye models, emmetropia, myopia, hyperopia, far points and axial-length calculations.',
    coverImage: cover('schematic-eye-refractive-states'),
    objectives: [
      'Use vergence and paraxial relationships with correct signs and units.',
      'Compare Gullstrand and reduced-eye models.',
      'Calculate and interpret emmetropia, myopia, hyperopia, far point and axial length.',
    ],
    sections: [
      {
        id: 'vergence-paraxial',
        title: 'Vergence and paraxial rays',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'schematic-models',
        title: 'Schematic-eye models',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'emmetropia',
        title: 'Emmetropia and emmetropization',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'myopia',
        title: 'Myopia and minus correction',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'hyperopia',
        title: 'Hyperopia and plus correction',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'far-point-axial',
        title: 'Far-point vergence and axial length',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
    ],
    facts: [],
  },
  {
    id: 'multifocal-foundations',
    courseId: 'dispensing-optics-ii',
    number: '02',
    shortTitle: 'Multifocal Foundations',
    title: 'Presbyopia, Bifocals and Trifocals',
    tone: 'coral',
    sourceNote: 'Rewritten only from the supplied OPT 370 course materials; see source register and ambiguity log.',
    description: 'Presbyopia, reading addition, bifocal construction and segment designs, NVP prism, jump, TCA, fitting and trifocals.',
    coverImage: cover('multifocal-foundations'),
    objectives: [
      'Explain presbyopia, additions and bifocal construction.',
      'Analyse segment geometry, NVP prism, jump and chromatic effects.',
      'Take and apply fitting, inset and trifocal measurements.',
    ],
    sections: [
      {
        id: 'presbyopia-add',
        title: 'Presbyopia and reading addition',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'construction-types',
        title: 'Bifocal construction types',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'segment-designs',
        title: 'Segment terminology and designs',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'nvp-prism',
        title: 'Near visual point and prism',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'jump-tca',
        title: 'Image jump and chromatic aberration',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'bifocal-fitting',
        title: 'Bifocal fitting and placement',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'trifocals',
        title: 'Trifocal additions and ratios',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
    ],
    facts: [],
  },
  {
    id: 'progressive-addition-lenses',
    courseId: 'dispensing-optics-ii',
    number: '03',
    shortTitle: 'Progressive Lenses',
    title: 'Progressive Addition Lenses',
    tone: 'teal',
    sourceNote: 'Rewritten only from the supplied OPT 370 course materials; see source register and ambiguity log.',
    description: 'PAL zones and designs, reference markings, patient and frame selection, fitting measurements, verification and troubleshooting.',
    coverImage: cover('progressive-addition-lenses'),
    objectives: [
      'Explain PAL zones, gradients and reference markings.',
      'Select and measure a stable frame for a specific wearer.',
      'Verify, deliver and troubleshoot PALs systematically.',
    ],
    sections: [
      {
        id: 'pal-principles',
        title: 'Progressive lens principles',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'pal-designs',
        title: 'PAL designs and task matching',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'reference-markings',
        title: 'Reference markings and layout',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'patient-frame',
        title: 'Patient and frame selection',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'measure-order',
        title: 'Measurement and ordering',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'verification-delivery',
        title: 'Verification and delivery',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'pal-troubleshooting',
        title: 'Troubleshooting PAL complaints',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
    ],
    facts: [],
  },
  {
    id: 'pd-and-dispensing',
    courseId: 'dispensing-optics-ii',
    number: '04',
    shortTitle: 'PD and Dispensing',
    title: 'Interpupillary Distance and Dispensing Quality',
    tone: 'violet',
    sourceNote: 'Rewritten only from the supplied OPT 370 course materials; see source register and ambiguity log.',
    description: 'Distance, near and monocular PD, manual and pupillometer methods, induced prism, dispensing checks and patient delivery.',
    coverImage: cover('pd-and-dispensing'),
    objectives: [
      'Measure distance, near and monocular PD by manual and instrument methods.',
      'Relate PD error to unwanted prism and patient symptoms.',
      'Complete a reproducible final dispensing and quality-control workflow.',
    ],
    sections: [
      {
        id: 'quality-mistakes',
        title: 'Common dispensing mistakes',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'pd-concepts',
        title: 'PD concepts and importance',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'pd-rule-methods',
        title: 'Manual PD-rule methods',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'pupillometer',
        title: 'Pupillometer measurement',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'near-pd',
        title: 'Near PD and convergence',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'pd-prism',
        title: 'PD error and unwanted prism',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'final-dispensing',
        title: 'Final dispensing and quality control',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
    ],
    facts: [],
  },
  {
    id: 'special-lenses',
    courseId: 'dispensing-optics-ii',
    number: '05',
    shortTitle: 'Special Lenses',
    title: 'Special Ophthalmic Lenses',
    tone: 'gold',
    sourceNote: 'Rewritten only from the supplied OPT 370 course materials; see source register and ambiguity log.',
    description: 'Lenticular and aspheric designs, aniseikonia and spectacle magnification, safety and filters, Fresnel prism and slab-off.',
    coverImage: cover('special-lenses'),
    objectives: [
      'Compare lenticular, aspheric and iseikonic designs.',
      'Calculate spectacle magnification and vertical imbalance.',
      'Fit and verify safety/filter, Fresnel and slab-off solutions.',
    ],
    sections: [
      {
        id: 'lenticular-aspheric',
        title: 'Lenticular and aspheric lenses',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'aniseikonia',
        title: 'Aniseikonia and iseikonic lenses',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'spectacle-magnification',
        title: 'Spectacle magnification',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'safety-filters',
        title: 'Safety lenses, filters and coatings',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'fresnel-prism',
        title: 'Fresnel prism fitting',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
      {
        id: 'slab-off',
        title: 'Bicentric grinding and slab-off',
        summary: 'Use the authored Notes V3 section for the full source-grounded explanation.',
        bullets: ['Core definitions and relationships', 'Worked application and error analysis', 'Measurement or clinical implications where applicable'],
        terms: ['See Notes V3 key terms'],
        clinical: 'Apply only within the limits and caveats stated in the supplied lecture sources.',
      },
    ],
    facts: [],
  },
];

export const opt370Modules: Module[] = opt370ModuleInputs.map((module) => ({
  ...module,
  sections: module.sections.map((section) => ({
    ...section,
    image: sectionFigure(module.id, module.title),
  })),
}));
