import { sectionImages } from '@/content/legacy/imageCatalog';
import type { Fact, Module, Section } from '@/lib/legacy/types';

const section = (id: string, title: string, summary: string, bullets: string[], terms: string[], clinical: string): Section => ({ id, title, summary, bullets, terms, clinical, image: sectionImages[id] });
const f = (section: string, q: string, a: string): Fact => ({ section, q, a });

const legacyModules: Array<Omit<Module, 'courseId' | 'lecturer' | 'sourceNote'>> = [
  {
    id: 'ocular-adnexa', number: '01', shortTitle: 'Ocular Adnexa', title: 'Ocular Adnexa & Lacrimal Apparatus', tone: 'teal',
    description: 'Eyelid landmarks, tissue layers, glands, lacrimal anatomy, tear film and drainage.',
    coverImage: { src: '/images/modules/ocular/cover.webp', width: 900, height: 506 },
    objectives: ['Identify the external landmarks and layers of the eyelids.', 'Relate each eyelid gland and muscle to its function.', 'Trace tear production and drainage from source to nose.'],
    sections: [
      section('landmarks', 'Landmarks & topography', 'The adnexa are structures close to the globe. The palpebral aperture lies between the lids, and its nasal and temporal angles are the canthi.', ['The upper lid has a tarsal part over the globe and an orbital part extending toward the eyebrow.', 'The superior palpebral sulcus marks the transition between the tarsal and orbital parts.', 'The lids protect the globe, contribute tear components, spread the tear film and direct tears medially.'], ['Palpebral aperture — opening between the lids', 'Canthus — angle where upper and lower lids meet', 'Tarsal portion — lid segment containing the tarsal plate'], 'A reduced palpebral aperture may follow weakness of the principal upper-lid elevator.'),
      section('muscles', 'Skin, lashes & muscles', 'Eyelid skin is exceptionally thin and mobile. Beneath it, orbicularis oculi closes the lids while levator palpebrae superioris and Müller muscle elevate the upper lid.', ['Lashes are arranged in two to three rows and trigger protective blinking.', 'Orbicularis has orbital, palpebral and lacrimal portions.', 'Levator is supplied by the superior division of CN III; Müller muscle is sympathetically supplied smooth muscle.'], ['Orbicularis oculi — striated lid-closing muscle', 'Levator palpebrae superioris — principal upper-lid elevator', 'Müller muscle — sympathetically supplied smooth muscle'], 'CN III palsy can produce marked ptosis; sympathetic interruption produces a milder ptosis.'),
      section('tarsus-glands', 'Tarsus, conjunctiva & glands', 'The tarsal plate gives the lid rigidity and houses meibomian glands. Posteriorly, conjunctiva lines the lids and reflects onto the globe at the fornices.', ['Meibomian glands are modified sebaceous glands that secrete tear-film lipid.', 'Goblet cells in conjunctival epithelium secrete mucin.', 'Zeiss glands are sebaceous glands associated with lashes; Moll glands are modified sweat glands.'], ['Tarsal plate — dense supporting tissue', 'Fornix — fold between palpebral and bulbar conjunctiva', 'Goblet cell — unicellular mucin-secreting gland'], 'Blocked meibomian glands destabilize the lipid layer and can increase evaporative dry eye.'),
      section('lower-lid-blood', 'Lower lid & blood supply', 'The lower lid resembles a smaller inverted upper lid but lacks an equivalent of the levator muscle and is less mobile.', ['Its supporting tissues become more lax with age.', 'Eyelid arteries are mainly branches of the ophthalmic artery.', 'Conjunctival venous drainage reaches divisions of the ophthalmic veins.'], ['Palpebral arcade — arterial network of the lids', 'Posterior palpebral arteries — supply the conjunctiva'], 'Age-related lid laxity can disturb apposition to the globe and tear drainage.'),
      section('lacrimal-gland', 'Lacrimal gland', 'The almond-shaped lacrimal gland occupies the superolateral orbit in a depression of the frontal bone and has orbital and palpebral portions.', ['Acini drain through progressively larger ducts into about 10–12 excretory ducts.', 'The ducts open into the superior conjunctival fornix.', 'Secretomotor parasympathetic fibres originate with CN VII and reach the gland through trigeminal branches.'], ['Acinus — secretory lobule', 'Orbital portion — larger superior part', 'Palpebral portion — smaller inferior part'], 'Inflammation or enlargement in the superolateral orbit may displace the globe inferomedially.'),
      section('tears', 'Tear film & drainage', 'The tear film has an outer lipid layer, a thick aqueous layer and a mucin-rich layer at the epithelial surface.', ['Lipid comes mainly from meibomian glands; aqueous from the lacrimal and accessory lacrimal glands; mucin from conjunctival goblet cells.', 'Tears move medially into puncta, canaliculi, the lacrimal sac and nasolacrimal duct before entering the inferior nasal meatus.', 'Blinking spreads tears and the lacrimal part of orbicularis assists drainage.'], ['Schirmer test — estimates aqueous tear production', 'Punctum — entry to the drainage system', 'Inferior nasal meatus — nasal destination of the nasolacrimal duct'], 'The slide states that normal production is primarily sympathetic; standard physiology describes parasympathetic secretomotor control as dominant.'),
    ],
    facts: [
      f('landmarks','What is the opening between the upper and lower eyelids called?','Palpebral aperture'), f('landmarks','What term describes the angle where the upper and lower lids meet?','Canthus'), f('landmarks','Which furrow separates the tarsal and orbital parts of the upper lid?','Superior palpebral sulcus'), f('landmarks','Which lid portion extends from the tarsus toward the eyebrow?','Orbital portion'), f('landmarks','Which upper-lid portion contains the tarsal plate and covers the globe?','Tarsal portion'), f('landmarks','Which function directs tears toward the medial drainage area?','Eyelid movement and tear distribution'),
      f('muscles','Why can eyelid skin fold rapidly during blinking?','It is very thin and loosely attached'), f('muscles','How are eyelashes commonly arranged at the lid margin?','In two to three rows'), f('muscles','Approximately how many lashes are on the upper lid in the deck?','About 150'), f('muscles','What type of muscle is orbicularis oculi?','Striated skeletal muscle'), f('muscles','Which orbicularis portion overlies extraorbital bone?','Orbital portion'), f('muscles','Which orbicularis portion produces voluntary closure and blinking?','Palpebral portion'), f('muscles','Which orbicularis portion lies behind the lacrimal sac?','Lacrimal portion'), f('muscles','Which nerve supplies levator palpebrae superioris?','Superior division of cranial nerve III'), f('muscles','What is the principal action of levator palpebrae superioris?','Elevation of the upper lid'), f('muscles','What type of tissue forms Müller muscle?','Smooth muscle'), f('muscles','What supplies Müller muscle?','Sympathetic fibres from the superior cervical ganglion'),
      f('tarsus-glands','What is the principal mechanical role of the tarsal plate?','It provides rigidity to the lid'), f('tarsus-glands','Which structures anchor the tarsal plate nasally and temporally?','Medial and lateral palpebral ligaments'), f('tarsus-glands','Which glands lie within the tarsal plate?','Meibomian glands'), f('tarsus-glands','About how many meibomian glands are described in the upper lid?','About 30'), f('tarsus-glands','What membrane covers the posterior lids and anterior globe?','Conjunctiva'), f('tarsus-glands','What are the two main conjunctival divisions?','Palpebral and bulbar conjunctiva'), f('tarsus-glands','Where do palpebral and bulbar conjunctiva reflect into one another?','At the superior and inferior fornices'), f('tarsus-glands','Which cells produce the mucin component of tears?','Conjunctival goblet cells'), f('tarsus-glands','Which sebaceous glands empty into eyelash follicles?','Glands of Zeiss'), f('tarsus-glands','Which lid-margin glands are modified sweat glands?','Glands of Moll'), f('tarsus-glands','Which glands provide accessory aqueous tear secretion?','Glands of Krause and Wolfring'),
      f('lower-lid-blood','Which upper-lid elevator has no lower-lid equivalent?','Levator palpebrae superioris'), f('lower-lid-blood','What common age-related change affects the lower lid?','Increasing laxity and sagging'), f('lower-lid-blood','Most eyelid arteries are branches of which artery?','Ophthalmic artery'), f('lower-lid-blood','Conjunctival veins ultimately drain through which venous system?','Ophthalmic veins'),
      f('lacrimal-gland','Where is the lacrimal gland located within the orbit?','Superolateral orbit'), f('lacrimal-gland','Which bone contains the lacrimal gland depression?','Frontal bone'), f('lacrimal-gland','What is the overall shape of the lacrimal gland?','Almond-shaped'), f('lacrimal-gland','What are the two portions of the lacrimal gland?','Orbital and palpebral portions'), f('lacrimal-gland','What are the secretory lobules of the lacrimal gland called?','Acini'), f('lacrimal-gland','How many excretory ducts commonly open into the conjunctival sac?','About 10–12'), f('lacrimal-gland','Which vessel supplies the lacrimal gland?','Lacrimal artery'), f('lacrimal-gland','Parasympathetic secretomotor fibres originate with which cranial nerve?','Facial nerve (CN VII)'),
      f('tears','Which tear-film layer is outermost?','Lipid layer'), f('tears','Which tear-film layer is the thickest?','Aqueous layer'), f('tears','Which tear-film layer lies closest to the epithelium?','Mucin-rich layer'), f('tears','What is the main source of tear-film lipid?','Meibomian glands'), f('tears','What is the main source of the aqueous tear layer?','Lacrimal and accessory lacrimal glands'), f('tears','What is the main source of tear-film mucin?','Conjunctival goblet cells'), f('tears','Where do tears go after the lacrimal sac?','Nasolacrimal duct'), f('tears','Approximately what fraction of tears may be lost by evaporation?','About 25%'), f('tears','Which muscle assists the lacrimal pump during lid closure?','Lacrimal portion of orbicularis oculi'), f('tears','Which clinical test crudely measures aqueous tear production?','Schirmer test'),
    ],
  },
  {
    id: 'aqueous-vitreous', number: '02', shortTitle: 'Aqueous & Vitreous', title: 'Aqueous Humour & Vitreous Body', tone: 'blue',
    description: 'Chambers, aqueous production and drainage, intraocular pressure, vitreous structure and ageing.',
    coverImage: { src: '/images/modules/aqueous/cover.webp', width: 900, height: 506 },
    objectives: ['Describe the chambers and transparent media of the eye.', 'Trace conventional and alternate aqueous outflow.', 'Relate vitreous anatomy and age-related change to clinical findings.'],
    sections: [
      section('media-chambers','Transparent media & chambers','The internal transparent media are the crystalline lens, aqueous humour and vitreous body. Aqueous occupies the anterior and posterior chambers.', ['The anterior chamber lies between cornea and iris and is about 0.2 mL.', 'The posterior chamber is a narrow space behind the iris and in front of the lens and zonules.', 'The chambers communicate through the pupil.'], ['Anterior chamber — cornea to iris', 'Posterior chamber — iris to lens/zonules', 'Aqueous humour — clear chamber fluid'], 'A shallow anterior chamber can increase the risk of angle closure.'),
      section('production','Functions, production & composition','Aqueous nourishes avascular tissues, removes metabolic waste and helps maintain ocular form and pressure.', ['It is produced mainly by active secretion from non-pigmented ciliary epithelium, with filtration and diffusion contributing.', 'New aqueous enters the posterior chamber.', 'The blood–aqueous barrier regulates movement from blood into the eye.'], ['Ciliary process — site of aqueous production', 'Non-pigmented epithelium — active secretory layer', 'Blood–aqueous barrier — controlled exchange interface'], 'Inflammation can add protein and cells to aqueous, producing flare and risking outflow obstruction.'),
      section('flow','Flow & drainage','Aqueous flows from ciliary processes through the posterior chamber and pupil into the anterior chamber.', ['About 90% leaves by the trabecular pathway: trabecular meshwork, Schlemm canal, collector channels and aqueous veins.', 'A smaller fraction follows uveoscleral and other routes.', 'A temperature difference between warmer iris/lens and cooler cornea creates convection currents.'], ['Trabecular meshwork — principal resistance site', 'Schlemm canal — circumferential drainage channel', 'Uveoscleral outflow — alternate route through ciliary tissues'], 'Impaired trabecular drainage can elevate intraocular pressure.'),
      section('iop','Intraocular pressure','IOP reflects the balance between aqueous formation, outflow resistance and episcleral venous pressure.', ['The deck gives an approximate normal range of 10–20 mmHg.', 'Anterior-chamber aqueous has a half-life of about 45 minutes.', 'Posture, time of day and external pressure can alter a measurement.'], ['Tonometer — instrument used to measure IOP', 'Episcleral venous pressure — downstream outflow pressure', 'Diurnal variation — change during the day'], 'IOP alone does not define glaucoma; optic-nerve damage and visual-field change matter.'),
      section('vitreous-anatomy','Vitreous anatomy & composition','The vitreous fills the posterior segment behind the lens and in front of the retina. It is a transparent gel, roughly 4 mL and about 99% water.', ['Its collagen–hyaluronic acid network gives gel structure.', 'Strong attachments occur at the vitreous base near the ora serrata, optic disc and lens periphery.', 'The hyaloid canal runs from optic disc toward the posterior lens and carried the fetal hyaloid artery.'], ['Hyaloid fossa — depression for the lens', 'Vitreous base — strongest attachment zone', 'Hyaloid canal — fetal vascular pathway'], 'The retrolental potential space may collect blood or exudate in disease.'),
      section('vitreous-clinical','Function, ageing & clinical change','Vitreous transmits light, supports the posterior lens and helps maintain retinal apposition.', ['Ageing causes liquefaction that often begins posteriorly.', 'Vitreoretinal adhesion weakens with age.', 'Acute posterior vitreous separation can cause flashes and floaters and may produce a retinal tear.'], ['Syneresis — vitreous liquefaction', 'Posterior vitreous detachment — separation from posterior retina', 'Photopsia — perception of flashes'], 'New flashes, floaters or a curtain-like field defect require urgent retinal assessment.'),
    ],
    facts: [
      f('media-chambers','Which three structures form the internal transparent media?','Crystalline lens, aqueous humour and vitreous body'), f('media-chambers','Which chambers contain aqueous humour?','Anterior and posterior chambers'), f('media-chambers','What is the approximate volume of the anterior chamber?','About 0.2 mL'), f('media-chambers','What is the approximate anteroposterior depth stated for the anterior chamber?','About 3.5 mm'), f('media-chambers','What forms the main posterior boundary of the anterior chamber?','Anterior iris and central lens region'), f('media-chambers','How is the posterior chamber shaped?','A narrow slit-like space'), f('media-chambers','What bounds the posterior chamber posteriorly?','Lens and suspensory ligaments'),
      f('production','What is the normal appearance of aqueous humour?','Clear fluid'), f('production','Which avascular structures receive nutrients from aqueous?','Cornea and crystalline lens'), f('production','What metabolic role does aqueous perform besides nutrient delivery?','Removal of waste products'), f('production','How does aqueous support ocular form?','It provides positive internal pressure'), f('production','Which ocular variable is strongly governed by aqueous dynamics?','Intraocular pressure'), f('production','Where is aqueous mainly produced?','Ciliary epithelium'), f('production','Which ciliary layer actively secretes aqueous?','Non-pigmented ciliary epithelium'), f('production','Into which chamber is fresh aqueous secreted?','Posterior chamber'), f('production','Which processes contribute to aqueous formation?','Active secretion, filtration and diffusion'),
      f('flow','Through what opening does aqueous pass from posterior to anterior chamber?','Pupil'), f('flow','Which barrier regulates entry of substances into aqueous?','Blood–aqueous barrier'), f('flow','What proportion of outflow uses the conventional pathway?','About 90%'), f('flow','Which structure is encountered first in conventional outflow at the angle?','Trabecular meshwork'), f('flow','What is the correct name of the circumferential drainage canal?','Canal of Schlemm'), f('flow','What follows Schlemm canal in the drainage sequence?','Collector channels'), f('flow','Which veins receive conventional aqueous outflow?','Aqueous and episcleral veins'), f('flow','What approximate proportion uses alternate drainage routes?','About 10%'), f('flow','What percentage of chamber volume is renewed each minute in the deck?','About 1–1.5%'), f('flow','How does aqueous cross the endothelium of Schlemm canal?','Through transcellular vacuoles'), f('flow','What drives thermal circulation in the anterior chamber?','A temperature difference between cornea and iris/lens'),
      f('iop','What is the approximate half-life of anterior-chamber aqueous?','About 45 minutes'), f('iop','What daily aqueous production is stated in the deck?','About 2.8 mL'), f('iop','What must happen to keep IOP stable?','Aqueous production and outflow must balance'), f('iop','What approximate normal IOP range is given?','10–20 mmHg'), f('iop','Which production factor helps determine IOP?','Rate of aqueous formation'), f('iop','Which outflow factor helps determine IOP?','Trabecular drainage rate'), f('iop','Which downstream pressure influences IOP?','Episcleral venous pressure'), f('iop','Which instrument measures intraocular pressure?','Tonometer'),
      f('vitreous-anatomy','Where is the vitreous body located?','Behind the lens and in front of the retina'), f('vitreous-anatomy','What is the lens-shaped depression in anterior vitreous called?','Hyaloid fossa'), f('vitreous-anatomy','Where can blood or exudate collect behind the lens?','Retrolental potential space'), f('vitreous-anatomy','Where is the strongest peripheral vitreous attachment?','Vitreous base near the ora serrata'), f('vitreous-anatomy','What happens to vitreolenticular attachment with age?','It weakens'), f('vitreous-anatomy','What is the width of the hyaloid canal stated in the deck?','About 1–2 mm'), f('vitreous-anatomy','What fetal vessel occupied the hyaloid canal?','Hyaloid artery'), f('vitreous-anatomy','What is the approximate vitreous volume?','About 4 mL'), f('vitreous-anatomy','What makes up approximately 99% of vitreous?','Water'),
      f('vitreous-clinical','What is the primary optical function of vitreous?','Transmission of light'), f('vitreous-clinical','How much refractive power does vitreous contribute?','Very little'), f('vitreous-clinical','Which lens surface is supported by vitreous?','Posterior surface'), f('vitreous-clinical','What retinal role does vitreous support?','Apposition of neural and pigment retinal layers'), f('vitreous-clinical','Where does age-related vitreous liquefaction often begin?','Posteriorly'), f('vitreous-clinical','Which serious condition may follow a vitreous-related retinal tear?','Retinal detachment'),
    ],
  },
  {
    id: 'blood-supply', number: '03', shortTitle: 'Blood Supply', title: 'Blood Supply to the Eye', tone: 'coral',
    description: 'Ophthalmic artery branches, retinal and uveal circulation, barriers, capillaries and clinical integration.',
    coverImage: { src: '/images/modules/blood/cover.webp', width: 900, height: 506 },
    objectives: ['Distinguish retinal from uveal vascular supply.', 'Compare short and long posterior ciliary arteries.', 'Explain ocular blood barriers and clinically important occlusions.'],
    sections: [
      section('arterial-origins','Arterial origins & two systems','The ophthalmic artery arises from the internal carotid artery and supplies the orbit and eye through retinal and ciliary branches.', ['The central retinal artery supplies the inner retina.', 'Posterior ciliary arteries supply the choroid, ciliary body, iris, outer retina indirectly and deeper optic nerve head.', 'This dual supply explains layer-specific injury after vascular occlusion.'], ['CRA — central retinal artery', 'SPCA — short posterior ciliary artery', 'LPCA — long posterior ciliary artery'], 'Retinal tissue has high oxygen and glucose needs and is vulnerable to interrupted perfusion.'),
      section('ciliary','Ciliary & choroidal circulation','Short posterior ciliary arteries form much of the posterior choriocapillaris, while two long posterior ciliary arteries run forward through the choroid.', ['Long posterior ciliary and anterior ciliary arteries contribute to the major arterial circle of the iris.', 'Short posterior ciliary arteries also supply the optic nerve head and circle of Zinn–Haller.', 'Choroidal venous blood drains mainly through vortex veins.'], ['Choriocapillaris — capillary bed of choroid', 'Major circle of iris — arterial anastomosis', 'Vortex vein — principal choroidal venous drainage'], 'Circumciliary flush in anterior uveitis reflects deep anterior ciliary circulation.'),
      section('retinal','Retinal circulation & FAZ','The central retinal artery enters the optic nerve behind the globe and branches across the retina with limited collateral overlap.', ['Retinal vessels nourish the inner two-thirds of retinal depth.', 'Photoreceptors and other outer retinal layers depend largely on choroidal diffusion.', 'The foveal avascular zone keeps vessels away from the optical centre.'], ['FAZ — foveal avascular zone', 'Arteriole — resistance vessel', 'Venule — low-pressure collecting vessel'], 'Few effective anastomoses make central retinal artery occlusion an ocular emergency.'),
      section('barriers','Blood–ocular barriers','Tight junctions regulate exchange between ocular blood and neural or epithelial tissues.', ['The inner blood–retina barrier is formed mainly by non-fenestrated retinal capillary endothelium.', 'The outer blood–retina barrier is formed by tight junctions between retinal pigment epithelial cells.', 'Choroidal and ciliary capillaries are fenestrated and relatively permeable.'], ['Fenestrated capillary — capillary with pores', 'Continuous capillary — non-fenestrated endothelium', 'RPE — retinal pigment epithelium'], 'Barrier breakdown can produce retinal oedema and visible leakage on angiography.'),
      section('microcirculation','Retinal microcirculation','Retinal arterioles are resistance vessels; capillaries are exchange vessels where cells and solutes pass close to neural tissue.', ['Arterioles near the optic nerve head have several smooth-muscle layers that thin peripherally.', 'Capillaries are only several micrometres wide and contain endothelial cells, pericytes and basement membrane.', 'Red cells deform to move through the narrow lumen.'], ['Pericyte — contractile capillary-associated cell', 'Basement membrane — supporting extracellular layer', 'Exchange vessel — site of nutrient and gas transfer'], 'Pericyte loss and barrier dysfunction are important features of diabetic retinopathy.'),
      section('clinical-blood','Clinical integration','The pattern of visual damage depends on which vascular system and retinal depth is affected.', ['Central retinal artery compromise primarily threatens inner retina.', 'Choroidal compromise threatens photoreceptors and outer retina.', 'Anterior ciliary inflammation produces a deeper circumcorneal injection than superficial conjunctivitis.'], ['Ischaemia — inadequate perfusion', 'Circumciliary flush — deep perilimbal redness', 'Anastomosis — connection between vessels'], 'Sudden painless monocular visual loss requires urgent assessment for retinal arterial occlusion.'),
    ],
    facts: [
      f('arterial-origins','The ophthalmic artery is a branch of which major artery?','Internal carotid artery'), f('arterial-origins','Which artery directly supplies the inner retina?','Central retinal artery'), f('arterial-origins','Which arteries form the principal uveal supply?','Posterior ciliary arteries'), f('arterial-origins','How many major perfusion systems are emphasized for the retina?','Two'), f('arterial-origins','Which retinal region is nourished by central retinal circulation?','Inner retinal layers'), f('arterial-origins','Which circulation indirectly nourishes the outer retina?','Choroidal circulation'), f('arterial-origins','Which three ophthalmic branches are emphasized in the deck?','Central retinal, long posterior ciliary and short posterior ciliary arteries'), f('arterial-origins','Which two substrates are highlighted as reasons tissue needs arterial supply?','Oxygen and glucose'), f('arterial-origins','Which artery is the immediate source of the ophthalmic artery?','Internal carotid artery'),
      f('ciliary','Which vessels give rise mainly to posterior choriocapillaris?','Short posterior ciliary arteries'), f('ciliary','Which vessels contribute mainly to anterior choriocapillaris?','Long posterior ciliary arteries'), f('ciliary','How many long posterior ciliary arteries are usually described?','Two, medial and lateral'), f('ciliary','Which arteries unite to form the major circle of the iris?','Long posterior ciliary and anterior ciliary arteries'), f('ciliary','How does most choroidal venous blood leave the eye?','Vortex veins'), f('ciliary','Which vessels supply choroid and indirectly the outer retina?','Short posterior ciliary arteries'), f('ciliary','Which vessels contribute to optic nerve head supply?','Short posterior ciliary arteries'), f('ciliary','Which arterial circle surrounds the optic nerve?','Circle of Zinn–Haller'), f('ciliary','Which arteries pass forward through the choroid?','Long posterior ciliary arteries'), f('ciliary','What redness pattern is associated with anterior uveitis?','Circumciliary flush'),
      f('retinal','Approximately where does the central retinal artery enter the optic nerve?','About 10 mm behind the globe'), f('retinal','Which vessel accompanies the central retinal artery at the optic nerve?','Central retinal vein'), f('retinal','What is notable about retinal arterial anastomoses?','They are few and provide limited redundancy'), f('retinal','Why can retinal arterial occlusion be rapidly damaging?','Limited collateral circulation permits ischaemia'), f('retinal','What fraction of retinal depth is supplied by retinal vessels?','Inner two-thirds'), f('retinal','Which tissue supplies most photoreceptor metabolism?','Choroid'), f('retinal','What does FAZ stand for?','Foveal avascular zone'), f('retinal','Why is the central fovea avascular?','To allow unimpeded light transmission'), f('retinal','What determines the retinal layers damaged by vascular occlusion?','Which vascular pathway is interrupted'), f('retinal','What sequence links small retinal arteries to veins?','Arterioles, capillaries and venules'),
      f('barriers','What cellular feature is fundamental to blood–ocular barriers?','Tight junctions'), f('barriers','Which substances readily cross ocular capillary beds because of lipid solubility?','Oxygen and carbon dioxide'), f('barriers','What determines how water crosses a capillary bed?','Capillary type and membrane properties'), f('barriers','Which ocular capillaries are fenestrated?','Choroidal and ciliary-body capillaries'), f('barriers','Which ocular capillaries are continuous and least permeable?','Retinal capillaries'), f('barriers','Which capillary type is not normally found in the eye?','Discontinuous capillary'), f('barriers','What can pass through the small pores described in continuous capillaries?','Molecules smaller than roughly 9 nm'), f('barriers','What is the approximate upper range stated for large capillary pores?','About 24–70 nm'), f('barriers','What forms the inner blood–retina barrier?','Tight retinal capillary endothelial junctions'), f('barriers','What forms the outer blood–retina barrier?','Tight junctions between RPE cells'),
      f('microcirculation','What is the approximate retinal arteriole diameter at the optic nerve head?','About 100 µm'), f('microcirculation','Which layers form a retinal arteriole wall?','Endothelium, basement membrane and smooth muscle'), f('microcirculation','How many smooth-muscle layers may be present near the optic nerve head?','About five to seven'), f('microcirculation','How many smooth-muscle layers commonly remain peripherally?','About one to two'), f('microcirculation','Why are retinal arterioles called resistance vessels?','They regulate vascular resistance'), f('microcirculation','What is the approximate retinal capillary diameter?','About 3.5–6 µm'), f('microcirculation','Which mural cells are found in retinal capillaries?','Pericytes'),
      f('clinical-blood','Why does anterior uveitis produce circumciliary flush?','Shared deep anterior ciliary vascular supply'), f('clinical-blood','Which retinal compartment is most threatened by central retinal artery occlusion?','Inner retina'), f('clinical-blood','Which retinal compartment is most threatened by choroidal hypoperfusion?','Outer retina and photoreceptors'), f('clinical-blood','How do red blood cells traverse narrow retinal capillaries?','They deform and squeeze through'),
    ],
  },
];


export const opt376Modules: Module[] = legacyModules.map((module) => ({
  ...module,
  courseId: 'neuro-anatomy',
  lecturer: module.id === 'blood-supply'
    ? 'Clement Afari, OD, MOptom, PhD · Chris Hudson, PhD, MCOptom, FAAO'
    : 'Supplied OPT 376 course deck',
  sourceNote: 'Rewritten from the supplied OPT 376 slides. Figures are drawn from the course decks and attributed educational sources. A correction note is included where slide wording conflicts with standard physiology.',
}));
