import type { QuestionBlueprint } from '@/lib/assessment/blueprint/types';

export const pdAndDispensingContentBlueprint: QuestionBlueprint = {
  id: 'pd-and-dispensing-candidate-v1',
  bankId: 'pd-and-dispensing-candidate',
  totalQuestions: 80,
  sectionTargets: {
    'final-dispensing': 7,
    'near-pd': 15,
    'pd-concepts': 13,
    'pd-prism': 9,
    'pd-rule-methods': 11,
    'pupillometer': 14,
    'quality-mistakes': 11,
  },
  formatTargets: {
    'extended_matching': 7,
    'image_hotspot': 5,
    'image_label': 4,
    'matching': 9,
    'multiple_response': 10,
    'open_response': 2,
    'ordering': 7,
    'short_answer': 4,
    'single_best_answer': 26,
    'true_false': 6,
  },
  bloomTargets: {
    'analyze': 7,
    'apply': 34,
    'create': 1,
    'evaluate': 3,
    'remember': 11,
    'understand': 24,
  },
  difficultyTargets: {
    'advanced': 10,
    'foundation': 26,
    'intermediate': 44,
  },
  stimulusTargets: {
    'table': 0,
    'clinical_vignette': 7,
    'comparison': 26,
    'diagram': 9,
    'error_analysis': 4,
    'pathway': 7,
    'text': 27,
  },
  minimumHigherOrderShare: 45 / 80,
  minimumQuestionsPerObjective: 2,
};

export const pdAndDispensingPracticeBlueprint = {
  id: 'pd-and-dispensing-practice-50-v1',
  bankId: 'pd-and-dispensing-candidate',
  totalQuestions: 50,
  sectionTargets: {
    'final-dispensing': 4,
    'near-pd': 9,
    'pd-concepts': 8,
    'pd-prism': 6,
    'pd-rule-methods': 7,
    'pupillometer': 9,
    'quality-mistakes': 7,
  },
  formatTargets: {
    'single_best_answer': 17,
    'true_false': 4,
    'multiple_response': 6,
    'ordering': 4,
    'matching': 5,
    'extended_matching': 4,
    'image_hotspot': 3,
    'image_label': 2,
    'short_answer': 3,
    'open_response': 2,
  },
} as const;
