import {
  aqueousLectureSource,
  openStaxVisionSource,
} from '@/content/question-bank/pilot/sources';
import type { LearningObjective } from '@/lib/assessment/types';

export const pilotObjectives: LearningObjective[] = [
  {
    schemaVersion: 1,
    id: 'aqueous-identify-chambers',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'media-chambers',
    statement: 'Identify the boundaries and contents of the anterior and posterior chambers.',
    targetBloomLevels: ['remember', 'understand'],
    tags: ['aqueous', 'chambers'],
    sourceIds: [aqueousLectureSource.id, openStaxVisionSource.id],
    reviewStatus: 'draft',
  },
  {
    schemaVersion: 1,
    id: 'aqueous-explain-production',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'production',
    statement: 'Explain how aqueous humour is produced and supports avascular ocular tissues.',
    targetBloomLevels: ['understand', 'apply'],
    tags: ['aqueous', 'production'],
    sourceIds: [aqueousLectureSource.id],
    reviewStatus: 'draft',
  },
  {
    schemaVersion: 1,
    id: 'aqueous-trace-conventional-outflow',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'flow',
    statement: 'Trace conventional aqueous outflow from the posterior chamber to episcleral veins.',
    targetBloomLevels: ['understand', 'apply'],
    tags: ['aqueous', 'outflow'],
    sourceIds: [aqueousLectureSource.id],
    reviewStatus: 'draft',
  },
  {
    schemaVersion: 1,
    id: 'aqueous-relate-iop-determinants',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'iop',
    statement: 'Relate aqueous formation, outflow resistance, and episcleral venous pressure to IOP.',
    targetBloomLevels: ['apply', 'analyze'],
    tags: ['aqueous', 'iop'],
    sourceIds: [aqueousLectureSource.id],
    reviewStatus: 'draft',
  },
  {
    schemaVersion: 1,
    id: 'vitreous-identify-anatomy',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'vitreous-anatomy',
    statement: 'Identify vitreous boundaries, attachments, and internal landmarks.',
    targetBloomLevels: ['remember', 'understand'],
    tags: ['vitreous', 'anatomy'],
    sourceIds: [aqueousLectureSource.id, openStaxVisionSource.id],
    reviewStatus: 'draft',
  },
  {
    schemaVersion: 1,
    id: 'vitreous-interpret-clinical-change',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'vitreous-clinical',
    statement: 'Interpret flashes and floaters using age-related vitreoretinal change.',
    targetBloomLevels: ['apply', 'analyze'],
    tags: ['vitreous', 'clinical'],
    sourceIds: [aqueousLectureSource.id],
    reviewStatus: 'draft',
  },
];
