import {
  aqueousLectureSource,
  openStaxVisionSource,
} from '@/content/question-bank/pilot/sources';
import type { AssessmentQuestion } from '@/lib/assessment/types';

const flowImage = {
  src: '/images/modules/aqueous/03-aqueous-flow.webp',
  alt: 'Anterior eye cross-section showing the cornea, iris, pupil, lens, and aqueous-filled chambers.',
  width: 458,
  height: 577,
};

export const pilotQuestions: AssessmentQuestion[] = [
  {
    schemaVersion: 1,
    id: 'aqueous-flow-sba-001',
    familyId: 'aqueous-conventional-outflow-sequence',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'flow',
    objectiveId: 'aqueous-identify-outflow-resistance',
    format: 'single_best_answer',
    stimulusType: 'pathway',
    bloomLevel: 'remember',
    difficulty: 'foundation',
    stem: 'Aqueous humour reaches its principal resistance site at which structure?',
    explanation: 'The trabecular meshwork provides the main resistance in conventional aqueous outflow before Schlemm canal.',
    noteAnchor: 'flow',
    misconceptionTags: ['aqueous-route-order'],
    sources: [aqueousLectureSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    estimatedSeconds: 45,
    options: [
      {
        id: 'trabecular-meshwork',
        text: 'Trabecular meshwork',
        rationale: 'This is the principal resistance site in conventional outflow.',
      },
      {
        id: 'posterior-chamber',
        text: 'Posterior chamber',
        rationale: 'Aqueous is secreted here but does not encounter its principal outflow resistance here.',
        misconceptionTag: 'aqueous-production-location',
      },
      {
        id: 'vitreous-base',
        text: 'Vitreous base',
        rationale: 'This is a strong vitreoretinal attachment and is not part of aqueous drainage.',
        misconceptionTag: 'aqueous-vitreous-confusion',
      },
      {
        id: 'choroid',
        text: 'Choroidal circulation',
        rationale: 'The choroid nourishes outer retina and is not the conventional drainage route.',
        misconceptionTag: 'aqueous-vascular-confusion',
      },
    ],
    correctOptionId: 'trabecular-meshwork',
  },
  {
    schemaVersion: 1,
    id: 'aqueous-production-mr-001',
    familyId: 'aqueous-functions-and-production',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'production',
    objectiveId: 'aqueous-explain-production',
    format: 'multiple_response',
    stimulusType: 'comparison',
    bloomLevel: 'understand',
    difficulty: 'intermediate',
    stem: 'Select the functions that aqueous humour performs in the healthy eye.',
    explanation: 'Aqueous nourishes avascular cornea and lens, removes waste, and contributes to ocular form and pressure.',
    noteAnchor: 'production',
    misconceptionTags: ['aqueous-function-confusion'],
    sources: [aqueousLectureSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    estimatedSeconds: 75,
    options: [
      {
        id: 'nourish-avascular-tissues',
        text: 'Nourish the cornea and crystalline lens',
        rationale: 'These avascular tissues depend on aqueous for metabolic exchange.',
      },
      {
        id: 'remove-metabolic-waste',
        text: 'Remove metabolic waste from anterior tissues',
        rationale: 'Aqueous flow carries waste away from avascular tissues.',
      },
      {
        id: 'maintain-ocular-form',
        text: 'Help maintain ocular form and intraocular pressure',
        rationale: 'The balance of formation and outflow contributes to pressure and globe form.',
      },
      {
        id: 'supply-inner-retina',
        text: 'Provide the direct arterial supply to the inner retina',
        rationale: 'The central retinal circulation, not aqueous, supplies the inner retina.',
        misconceptionTag: 'aqueous-retinal-supply-confusion',
      },
    ],
    correctOptionIds: [
      'nourish-avascular-tissues',
      'remove-metabolic-waste',
      'maintain-ocular-form',
    ],
    minimumSelections: 3,
    maximumSelections: 3,
  },
  {
    schemaVersion: 1,
    id: 'aqueous-flow-ordering-001',
    familyId: 'aqueous-conventional-outflow-sequence',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    format: 'ordering',
    stimulusType: 'pathway',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Arrange the conventional aqueous pathway from its chamber of secretion to venous drainage.',
    explanation: 'Aqueous is secreted into the posterior chamber, crosses the pupil, and exits through the trabecular and venous pathway.',
    noteAnchor: 'flow',
    misconceptionTags: ['aqueous-route-order'],
    sources: [aqueousLectureSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    estimatedSeconds: 90,
    items: [
      { id: 'posterior-chamber', text: 'Posterior chamber', rationale: 'Fresh aqueous enters this chamber.' },
      { id: 'pupil', text: 'Pupil', rationale: 'Aqueous passes through the pupil to reach the anterior chamber.' },
      { id: 'anterior-chamber', text: 'Anterior chamber', rationale: 'Aqueous circulates here before reaching the angle.' },
      { id: 'trabecular-meshwork', text: 'Trabecular meshwork', rationale: 'This is the main conventional resistance site.' },
      { id: 'schlemm-canal', text: 'Schlemm canal', rationale: 'This circumferential channel receives trabecular outflow.' },
      { id: 'collector-channels', text: 'Collector channels', rationale: 'These connect Schlemm canal to aqueous veins.' },
      { id: 'episcleral-veins', text: 'Episcleral veins', rationale: 'These receive conventional outflow downstream.' },
    ],
    correctOrder: [
      'posterior-chamber',
      'pupil',
      'anterior-chamber',
      'trabecular-meshwork',
      'schlemm-canal',
      'collector-channels',
      'episcleral-veins',
    ],
  },
  {
    schemaVersion: 1,
    id: 'aqueous-flow-matching-001',
    familyId: 'aqueous-structure-function',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    format: 'matching',
    stimulusType: 'comparison',
    bloomLevel: 'understand',
    difficulty: 'foundation',
    stem: 'Match each aqueous-related structure to its principal role.',
    explanation: 'Ciliary epithelium produces aqueous, the pupil connects chambers, and the trabecular pathway drains most aqueous.',
    noteAnchor: 'flow',
    misconceptionTags: ['aqueous-structure-function'],
    sources: [aqueousLectureSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    prompts: [
      { id: 'non-pigmented-epithelium', text: 'Non-pigmented ciliary epithelium' },
      { id: 'pupil', text: 'Pupil' },
      { id: 'trabecular-meshwork', text: 'Trabecular meshwork' },
    ],
    choices: [
      { id: 'active-secretion', text: 'Main active secretory layer', rationale: 'The non-pigmented epithelium actively secretes aqueous.' },
      { id: 'chamber-connection', text: 'Connection between posterior and anterior chambers', rationale: 'Aqueous passes through the pupil.' },
      { id: 'outflow-resistance', text: 'Principal conventional outflow resistance', rationale: 'Resistance is concentrated in the trabecular region.' },
    ],
    correctMatches: {
      'non-pigmented-epithelium': 'active-secretion',
      pupil: 'chamber-connection',
      'trabecular-meshwork': 'outflow-resistance',
    },
  },
  {
    schemaVersion: 1,
    id: 'aqueous-iop-extended-matching-001',
    familyId: 'aqueous-iop-determinants',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'iop',
    objectiveId: 'aqueous-relate-iop-determinants',
    format: 'extended_matching',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'analyze',
    difficulty: 'advanced',
    stem: 'For each observation, choose the aqueous-dynamic factor most directly involved.',
    explanation: 'IOP reflects aqueous formation, resistance to outflow, and downstream episcleral venous pressure.',
    noteAnchor: 'iop',
    misconceptionTags: ['iop-single-factor-model'],
    sources: [aqueousLectureSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    estimatedSeconds: 120,
    options: [
      { id: 'formation-rate', text: 'Aqueous formation rate', rationale: 'Ciliary epithelial secretion determines formation.' },
      { id: 'trabecular-resistance', text: 'Trabecular outflow resistance', rationale: 'Increased resistance impedes conventional outflow.' },
      { id: 'episcleral-pressure', text: 'Episcleral venous pressure', rationale: 'This is the downstream pressure for conventional drainage.' },
      { id: 'vitreous-liquefaction', text: 'Vitreous liquefaction', rationale: 'Syneresis is not a primary determinant of aqueous IOP balance.' },
      { id: 'retinal-perfusion', text: 'Central retinal perfusion', rationale: 'Retinal perfusion is clinically important but not one of the three aqueous determinants listed.' },
    ],
    stems: [
      { id: 'secretion-reduced', text: 'Ciliary epithelial secretion is pharmacologically reduced.' },
      { id: 'meshwork-obstructed', text: 'Material accumulates within the trabecular pathway.' },
      { id: 'venous-pressure-raised', text: 'Downstream episcleral venous pressure rises.' },
    ],
    correctAnswers: {
      'secretion-reduced': 'formation-rate',
      'meshwork-obstructed': 'trabecular-resistance',
      'venous-pressure-raised': 'episcleral-pressure',
    },
  },
  {
    schemaVersion: 1,
    id: 'aqueous-flow-hotspot-001',
    familyId: 'aqueous-angle-anatomy',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'flow',
    objectiveId: 'aqueous-trace-conventional-outflow',
    format: 'image_hotspot',
    stimulusType: 'diagram',
    bloomLevel: 'apply',
    difficulty: 'intermediate',
    stem: 'Select the iridocorneal angle region where conventional aqueous outflow begins.',
    explanation: 'The trabecular meshwork lies at the peripheral anterior chamber angle between cornea and iris.',
    noteAnchor: 'flow',
    misconceptionTags: ['aqueous-angle-location'],
    sources: [aqueousLectureSource, openStaxVisionSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    image: flowImage,
    regions: [
      {
        id: 'iridocorneal-angle',
        label: 'Iridocorneal angle',
        interactionLabel: 'Upper-left peripheral marked region',
        marker: 'A',
        x: 0.08,
        y: 0.36,
        width: 0.18,
        height: 0.16,
      },
      {
        id: 'central-pupil',
        label: 'Central pupil',
        interactionLabel: 'Central marked region',
        marker: 'B',
        x: 0.35,
        y: 0.38,
        width: 0.18,
        height: 0.16,
      },
      {
        id: 'anterior-lens',
        label: 'Anterior lens',
        interactionLabel: 'Right-of-centre marked region',
        marker: 'C',
        x: 0.62,
        y: 0.38,
        width: 0.18,
        height: 0.16,
      },
    ],
    correctRegionIds: ['iridocorneal-angle'],
  },
  {
    schemaVersion: 1,
    id: 'aqueous-chambers-label-001',
    familyId: 'aqueous-chamber-boundaries',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'media-chambers',
    objectiveId: 'aqueous-identify-chambers',
    format: 'image_label',
    stimulusType: 'diagram',
    bloomLevel: 'understand',
    difficulty: 'foundation',
    stem: 'Label the principal anterior-segment structures that bound the aqueous chambers.',
    explanation: 'The cornea, iris, and lens define the principal relationships of the anterior and posterior chambers.',
    noteAnchor: 'media-chambers',
    misconceptionTags: ['aqueous-chamber-boundaries'],
    sources: [aqueousLectureSource, openStaxVisionSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    image: flowImage,
    targets: [
      { id: 'cornea-target', label: 'Anterior transparent boundary', x: 0.16, y: 0.28 },
      { id: 'iris-target', label: 'Pigmented diaphragm', x: 0.37, y: 0.47 },
      { id: 'lens-target', label: 'Posterior transparent structure', x: 0.61, y: 0.43 },
    ],
    labels: [
      { id: 'cornea', text: 'Cornea', rationale: 'The cornea forms the anterior boundary of the anterior chamber.' },
      { id: 'iris', text: 'Iris', rationale: 'The iris separates the anterior and posterior chambers except at the pupil.' },
      { id: 'lens', text: 'Crystalline lens', rationale: 'The lens contributes to the posterior boundary of the posterior chamber.' },
    ],
    correctLabels: {
      'cornea-target': 'cornea',
      'iris-target': 'iris',
      'lens-target': 'lens',
    },
  },
  {
    schemaVersion: 1,
    id: 'aqueous-iop-short-answer-001',
    familyId: 'aqueous-iop-measurement',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'iop',
    objectiveId: 'aqueous-identify-iop-measurement',
    format: 'short_answer',
    stimulusType: 'text',
    bloomLevel: 'remember',
    difficulty: 'foundation',
    stem: 'Name the instrument used to measure intraocular pressure.',
    explanation: 'A tonometer measures intraocular pressure; the measurement procedure is tonometry.',
    noteAnchor: 'iop',
    misconceptionTags: [],
    sources: [aqueousLectureSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    acceptedAnswers: ['tonometer', 'a tonometer'],
    normalization: {
      trim: true,
      caseInsensitive: true,
      collapseWhitespace: true,
      ignoreTerminalPunctuation: true,
    },
  },
  {
    schemaVersion: 1,
    id: 'vitreous-clinical-open-response-001',
    familyId: 'vitreous-ageing-clinical-reasoning',
    courseId: 'neuro-anatomy',
    moduleId: 'aqueous-vitreous',
    sectionId: 'vitreous-clinical',
    objectiveId: 'vitreous-interpret-clinical-change',
    format: 'open_response',
    stimulusType: 'clinical_vignette',
    bloomLevel: 'analyze',
    difficulty: 'advanced',
    stem: 'Explain why new flashes, floaters, or a curtain-like field defect require urgent retinal assessment.',
    explanation: 'Age-related vitreous separation can create retinal traction or a tear that may progress to retinal detachment.',
    noteAnchor: 'vitreous-clinical',
    misconceptionTags: ['benign-floater-assumption'],
    sources: [aqueousLectureSource],
    author: 'Optometry Study Hub pilot team',
    reviewStatus: 'draft',
    version: 1,
    sampleAnswer: 'Acute vitreoretinal traction may tear the retina, allowing fluid to produce a retinal detachment and threaten vision.',
    rubric: [
      'Links vitreous separation or traction to retinal tearing.',
      'Explains that a tear can progress to retinal detachment.',
      'Recognises the potential for urgent sight-threatening disease.',
    ],
    autoGraded: false,
  },
];
